package workspace

import (
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/gregberns/harmonik/internal/core"
	tmux "github.com/gregberns/harmonik/internal/lifecycle/tmux"
)

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func writeRemoteFile(ctx context.Context, runner tmux.CommandRunner, absPath string, content []byte) error {
	dir := filepath.Dir(absPath)
	b64 := base64.StdEncoding.EncodeToString(content)
	script := fmt.Sprintf("mkdir -p %s && printf %%s %s | base64 -d > %s",
		shellSingleQuote(dir), shellSingleQuote(b64), shellSingleQuote(absPath))
	out, err := runner.Command(ctx, "sh", "-lc", script).CombinedOutput()
	if err != nil {
		return fmt.Errorf("workspace: writeRemoteFile %s: %w\nremote: %s", absPath, err, out)
	}
	return nil
}

func removeRemoteFile(ctx context.Context, runner tmux.CommandRunner, absPath string) error {
	script := fmt.Sprintf("rm -f %s", shellSingleQuote(absPath))
	out, err := runner.Command(ctx, "sh", "-lc", script).CombinedOutput()
	if err != nil {
		return fmt.Errorf("workspace: removeRemoteFile %s: %w\nremote: %s", absPath, err, out)
	}
	return nil
}

// WriteFileVia writes content to absPath either onto the worker (runner != nil)
// or onto box A's local filesystem (runner == nil, byte-identical to a plain
// os.MkdirAll+os.WriteFile — NFR7). Generic content-agnostic sibling of
// WriteReviewTargetVia/WriteAgentTaskVia for callers with no dedicated payload
// type (e.g. the DOT cognition-gate task brief, hk-9fe2).
func WriteFileVia(ctx context.Context, runner tmux.CommandRunner, absPath string, content []byte, perm os.FileMode) error {
	if runner == nil {
		if err := os.MkdirAll(filepath.Dir(absPath), core.HarmonikDirMode); err != nil {
			return fmt.Errorf("workspace: WriteFileVia mkdir: %w", err)
		}
		return os.WriteFile(absPath, content, perm)
	}
	return writeRemoteFile(ctx, runner, absPath, content)
}

// RemoveFileVia removes absPath either on the worker (runner != nil) or on box
// A's local filesystem (runner == nil, byte-identical to os.Remove — NFR7).
// Generic content-agnostic sibling of RemoveReviewVerdictVia for callers with
// no dedicated path helper (e.g. the DOT cognition-gate verdict, hk-9fe2).
func RemoveFileVia(ctx context.Context, runner tmux.CommandRunner, absPath string) error {
	if runner == nil {
		return os.Remove(absPath)
	}
	return removeRemoteFile(ctx, runner, absPath)
}

// WriteReviewTargetVia writes the per-launch review-target.md either onto the
// worker (runner != nil) or onto box A's local filesystem (runner == nil,
// byte-identical to WriteReviewTarget — NFR7).
//
// On a REMOTE DOT-mode run the reviewer node runs in the WORKER's worktree, so a
// box-A-local WriteReviewTarget lands the reviewer brief on the wrong machine —
// box A grows an orphan .harmonik tree at the worker's mirror path and the worker
// reviewer never receives its instruction, idles, and writes no review.json
// ("reviewer node produced no verdict"). Routing the write through the runner
// mirrors WriteAgentTaskVia and puts the brief on the worker where the reviewer
// (and the paste-inject stat check) look for it.
//
// The content is generated by the SAME buildReviewTargetContent used by the local
// path, so the bytes are identical to what WriteReviewTarget writes today. Like
// WriteAgentTaskVia, the remote path always writes the current-iteration content
// (a remote worktree is created fresh per run; there is never a prior remote
// review-target.md to preserve).
func WriteReviewTargetVia(ctx context.Context, runner tmux.CommandRunner, payload ReviewTargetPayload) error {
	if runner == nil {
		return WriteReviewTarget(payload)
	}

	target := ReviewTargetPath(payload.WorkspacePath)
	content := buildReviewTargetContent(payload)
	if err := writeRemoteFile(ctx, runner, target, []byte(content)); err != nil {
		return fmt.Errorf("workspace: WriteReviewTargetVia: %w", err)
	}
	return nil
}

// RemoveReviewVerdictVia removes any stale .harmonik/review.json either on the
// worker (runner != nil) or on box A's local filesystem (runner == nil,
// byte-identical to the os.Remove call it replaces — NFR7). Tolerates a missing
// file (rm -f / os.Remove of an absent path). Callers discard the error, as the
// stale-verdict cleanup is best-effort.
func RemoveReviewVerdictVia(ctx context.Context, runner tmux.CommandRunner, workspacePath string) error {
	verdictPath := ReviewVerdictPath(workspacePath)
	if runner == nil {
		return os.Remove(verdictPath)
	}
	return removeRemoteFile(ctx, runner, verdictPath)
}

// MaterializeClaudeSettingsVia writes the hook-bridge settings.json either onto
// the worker (runner != nil) or onto box A's local filesystem (runner == nil,
// byte-identical to MaterializeClaudeSettings — NFR7).
//
// For the REMOTE path the merge-with-existing semantics of CHB-004 are NOT
// reproduced: a freshly-created remote worktree never carries a pre-existing
// .claude/settings.json (the worktree is created clean from the base SHA per
// B7), so the bridge-only content is the correct and complete file. This avoids
// a remote read-merge round-trip; the settings content is identical to what the
// local "file absent" branch of MaterializeClaudeSettings produces.
//
// daemonBinaryPath MUST be the WORKER's harmonik path for a remote run (the
// hook "command" field is executed ON THE WORKER); the caller resolves it.
func MaterializeClaudeSettingsVia(ctx context.Context, runner tmux.CommandRunner, workspacePath, daemonBinaryPath, sessionLogPath string) error {
	if runner == nil {
		return MaterializeClaudeSettings(workspacePath, daemonBinaryPath, sessionLogPath)
	}

	settingsPath := ClaudeSettingsPath(workspacePath)
	merged := buildBridgeOnlySettings(daemonBinaryPath)
	delete(merged, "disableAllHooks") // parity with the local path (CHB-004)

	content, err := marshalSettings(merged)
	if err != nil {
		return fmt.Errorf("workspace: MaterializeClaudeSettingsVia: marshal: %w", err)
	}
	if err := writeRemoteFile(ctx, runner, settingsPath, content); err != nil {
		return fmt.Errorf("workspace: MaterializeClaudeSettingsVia: %w", err)
	}
	return nil
}

// WriteAgentTaskVia writes the per-launch agent-task.md either onto the worker
// (runner != nil) or onto box A's local filesystem (runner == nil,
// byte-identical to WriteAgentTask — NFR7).
//
// The Body-non-empty validation matches WriteAgentTask (ErrTaskFileEmpty). The
// ReAttach short-circuit is intentionally NOT reproduced on the remote path: a
// remote worktree is created fresh per run, so there is never a prior remote
// agent-task.md to re-attach to; always writing the current (run, phase,
// iteration) content is correct.
func WriteAgentTaskVia(ctx context.Context, runner tmux.CommandRunner, workspacePath string, payload AgentTaskPayload) error {
	if runner == nil {
		return WriteAgentTask(workspacePath, payload)
	}
	if strings.TrimSpace(payload.Body) == "" {
		return fmt.Errorf("%w: payload.Body is empty for bead %q run %q",
			ErrTaskFileEmpty, payload.BeadID, payload.RunID)
	}

	target := AgentTaskPath(workspacePath)
	content := buildAgentTaskContent(payload)
	if strings.TrimSpace(content) == "" {
		return fmt.Errorf("%w: constructed content is empty for bead %q run %q",
			ErrTaskFileEmpty, payload.BeadID, payload.RunID)
	}
	if err := writeRemoteFile(ctx, runner, target, []byte(content)); err != nil {
		return fmt.Errorf("workspace: WriteAgentTaskVia: %w", err)
	}
	return nil
}

// EnsureWorktreeTrustVia pre-seeds the trust entry for worktreePath either in
// the WORKER's ~/.claude.json (runner != nil) or box A's (runner == nil,
// byte-identical to EnsureWorktreeTrust — NFR7).
//
// # Why the remote path is a single idempotent shell upsert
//
// Unlike settings.json and agent-task.md (worktree-relative writes), the trust
// entry lives in the worker user's HOME config (~/.claude.json), keyed by the
// ABSOLUTE worktree path AFTER realpath() normalization — Claude Code looks the
// key up under its own realpath() of the cwd. Box A cannot compute the worker's
// realpath() without a round-trip, and the daemon must NOT clobber a worker
// ~/.claude.json that may carry the operator's own projects/auth. So the remote
// path runs a small, idempotent, dependency-light shell upsert ON THE WORKER
// that (a) realpath-normalizes the worktree path on the worker itself, (b)
// read-merge-writes ~/.claude.json setting
// projects[<realpath>].hasTrustDialogAccepted = true, preserving every other
// key, and (c) is a no-op when already trusted.
//
// The upsert is performed by a small Python program (python3 is present on the
// macOS worker — verified by probe). Python's json module is stdlib, so no extra
// install is needed.
//
// # Python floor: 3.6
//
// The program uses f-strings in its lock-timeout diagnostic, which need python
// 3.6 or later. Everything else in it (os.replace, time.monotonic) needs only
// 3.3. The floor is safe on the worker this runs on: macOS first shipped a
// python3 at Catalina and it was 3.7, and every macOS since has shipped 3.8 or
// later. A worker below the floor also fails loudly rather than silently — the
// program is rejected at parse time with a SyntaxError on every launch, not on
// some rare branch. Rewriting the diagnostic with .format() would return the
// floor to 3.3 at the cost of a message that is harder to read and easier to get
// wrong, which is the wrong trade for a floor nothing can reach.
//
// # What is interpolated and what rides argv
//
// The worktree path rides ARGV — the program reads it from sys.argv[1] and it is
// never interpolated into the program text, so it needs no escaping here.
//
// The config path and the lock budget ARE interpolated into the program text, by
// workerConfigProgramPrelude. They go in through %q, which emits a Go
// double-quoted literal whose escaping python's lexer reads the same way, so a
// path with a quote, a backslash or a newline in it stays one string literal and
// cannot close the literal and inject statements.
//
// The program text itself never reaches a shell: it rides stdin. The single-quote
// wrap that an earlier version of this comment described belonged to a retired
// `python3 -c <prog>` form.
func EnsureWorktreeTrustVia(ctx context.Context, runner tmux.CommandRunner, worktreePath string) error {
	if runner == nil {
		return EnsureWorktreeTrust(worktreePath)
	}

	cmd := runner.Command(ctx, "python3", "-", worktreePath)
	cmd.Stdin = bytes.NewReader([]byte(workerTrustUpsertProgram(claudeConfigPathForWorker(), defaultTrustLockTimeout)))
	out, err := cmd.CombinedOutput()
	if err != nil {
		if workerConfigLockTimedOut(err) {
			return fmt.Errorf("%w\nremote: %s", ErrTrustLockTimeout, out)
		}
		if workerConfigUnparseable(err) {
			return fmt.Errorf("%w\nremote: %s", ErrTrustConfigUnparseable, out)
		}
		return fmt.Errorf("workspace: EnsureWorktreeTrustVia %s: %w\nremote: %s", worktreePath, err, out)
	}
	return nil
}

const workerConfigLockTimeoutExit = 75

const workerConfigUnparseableExit = 65

func workerConfigLockTimedOut(err error) bool {
	var exitErr *exec.ExitError
	return errors.As(err, &exitErr) && exitErr.ExitCode() == workerConfigLockTimeoutExit
}

func workerConfigUnparseable(err error) bool {
	var exitErr *exec.ExitError
	return errors.As(err, &exitErr) && exitErr.ExitCode() == workerConfigUnparseableExit
}

func workerConfigProgramPrelude(cfgPathForWorker string, lockTimeout time.Duration) string {
	return fmt.Sprintf(workerConfigProgramPreludeTemplate,
		cfgPathForWorker,
		lockTimeout.Seconds(),
		trustLockRetryInterval.Seconds(),
		workerConfigUnparseableExit,
		workerConfigLockTimeoutExit,
	)
}

const workerConfigProgramPreludeTemplate = `
import errno, fcntl, json, os, sys, tempfile, time

# Step 1 of the config-path precedence, decided by the caller and baked in as a
# value. "" means the caller had nothing to send, so this machine — the one that
# owns the file — resolves steps 2 and 3 from its own environment.
cfg_path = %[1]q
if not cfg_path:
    cfg_home = os.environ.get("CLAUDE_CONFIG_HOME", "")
    if cfg_home:
        cfg_path = os.path.join(cfg_home, ".claude.json")
    else:
        cfg_path = os.path.join(os.path.expanduser("~"), ".claude.json")
lock_path = cfg_path + ".lock"
lock_timeout = %[2]v
lock_interval = %[3]v

def load_cfg():
    # Two cases legitimately mean "start fresh", and both hold nothing worth
    # keeping: a MISSING file, and a literal "null" body. Every other way this
    # read can fail means a file exists with content we cannot understand, and
    # the only safe move is to leave it alone. Returning {} for those would send
    # the caller on to write a fresh config over the top, discarding every other
    # project entry and every other key on this machine. The in-process sibling
    # draws the line in the same place; see readClaudeConfigMap and
    # ErrTrustConfigUnparseable.
    try:
        with open(cfg_path) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        return {}
    except ValueError:
        sys.stderr.write(
            f"harmonik: {cfg_path} is not valid JSON, so the trust entry was not "
            f"written and the file was left exactly as it is. A partial read of "
            f"another writer's rewrite looks like this and clears on its own; a "
            f"file that stays unreadable needs a look.\n"
        )
        sys.exit(%[4]d)
    if cfg is None:
        # A literal "null" body parses without error and holds nothing, so there
        # is nothing to lose by treating it as empty. The in-process sibling
        # makes the same exception for the same reason; see readClaudeConfigMap.
        # Every OTHER non-object -- an array, a string, a number -- is a file
        # with content we do not understand, and overwriting it would discard it.
        return {}
    if not isinstance(cfg, dict):
        sys.stderr.write(
            f"harmonik: {cfg_path} holds a JSON {type(cfg).__name__} where an "
            f"object is required, so the trust entry was not written and the file "
            f"was left exactly as it is.\n"
        )
        sys.exit(%[4]d)
    return cfg

def acquire_bounded(fd):
    # Same shape as internal/workspace acquireExclusiveBounded: retry the
    # NON-blocking LOCK_EX until it succeeds or the budget runs out, then fail
    # loudly. Only EWOULDBLOCK counts as contention, exactly as the Go side has
    # it; every other errno (EBADF, EACCES, ...) is a real fault and is raised at
    # once rather than retried for the whole budget and then misreported as a
    # lock timeout. Two differences from the Go side that do not change the
    # outcome: this uses a monotonic clock, so a wall-clock step cannot stretch
    # or shrink the budget, and its deadline test fires AT the deadline where Go
    # fires just after it — at most one poll interval apart.
    deadline = time.monotonic() + lock_timeout
    while True:
        try:
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
            return
        except OSError as exc:
            if exc.errno != errno.EWOULDBLOCK:
                raise
            if time.monotonic() >= deadline:
                sys.stderr.write(
                    f"workspace: write-lock acquire timed out after {lock_timeout}s "
                    f"(contended {cfg_path})\n"
                    f"lock file: {lock_path}\n"
                    f"another process still holds this lock. Find it with: lsof {lock_path}\n"
                    f"a stale claude, harmonik daemon or go test binary is the usual holder.\n")
                sys.exit(%[5]d)
            time.sleep(lock_interval)

def write_cfg(cfg):
    d = os.path.dirname(cfg_path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".claude.json.tmp-")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(cfg, f, indent=2)
            f.write("\n")
        os.replace(tmp, cfg_path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
`

func workerTrustUpsertProgram(cfgPathForWorker string, lockTimeout time.Duration) string {
	return workerConfigProgramPrelude(cfgPathForWorker, lockTimeout) + workerTrustUpsertProgramBody
}

const workerTrustUpsertProgramBody = `
arg = sys.argv[1]
if len(arg) >= 2 and arg[0] == "'" and arg[-1] == "'":
    arg = arg[1:-1]
wt = os.path.realpath(arg)

def is_trusted(cfg):
    projects = cfg.get("projects")
    if not isinstance(projects, dict):
        return False
    entry = projects.get(wt)
    return isinstance(entry, dict) and entry.get("hasTrustDialogAccepted") is True

# Fast path: probe WITHOUT the lock; a no-op when already trusted.
if is_trusted(load_cfg()):
    sys.exit(0)

# Write path: hold LOCK_EX on the sidecar lockfile across the whole
# read-modify-write so concurrent writers never lose each other's keys.
lock_fd = os.open(lock_path, os.O_CREAT | os.O_RDWR, 0o600)
try:
    acquire_bounded(lock_fd)
    # Re-read UNDER the lock: another writer may have trusted this key (or added
    # other keys) between the lock-free probe and acquiring the lock.
    cfg = load_cfg()
    if is_trusted(cfg):
        sys.exit(0)
    projects = cfg.get("projects")
    if not isinstance(projects, dict):
        projects = {}
        cfg["projects"] = projects
    entry = projects.get(wt)
    if not isinstance(entry, dict):
        entry = {}
        projects[wt] = entry
    entry["hasTrustDialogAccepted"] = True
    write_cfg(cfg)
finally:
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_UN)
    except OSError:
        pass
    os.close(lock_fd)
`

// PrepareIsolatedClaudeConfigDirVia provisions a PRIVATE, per-launch Claude Code
// config directory for a REMOTE run ON THE WORKER and returns its worker-absolute
// path, ready to be exported to the spawned process as CLAUDE_CONFIG_DIR
// (hk-qxvc2). It is the SSH-aware sibling of PrepareIsolatedClaudeConfigDir: a nil
// runner delegates to the in-process (box-A-local) function, byte-identical to
// today (NFR7); a non-nil runner performs the SAME preparation on the worker.
//
// # WARNING — the LOCAL sibling was reverted (hk-8juwz)
//
// The claude:LOCAL isolation this mirrors is GONE: relocating CLAUDE_CONFIG_DIR
// moves the whole ~/.claude surface, and a local claude launched that way reported
// "Not logged in · Please run /login" (plus it lost ~/.claude/settings.json's
// skipDangerousModePermissionPrompt and parked on the bypass modal). The REMOTE
// path here is untouched but has NOT been live-tested for the same auth defect —
// if a worker's claude ever stalls at agent_ready or reports "Not logged in",
// suspect this first.
//
// # Why the remote path is needed
//
// Claude Code >= 2.1.214 renders a first-run onboarding/theme modal at Stage 1
// (BEFORE SessionStart) unless the config it reads records onboarding as complete.
// The LOCAL path once isolated a private config dir for this reason, but that was
// reverted (see the WARNING above) — a local claude now reads the operator's shared
// ~/.claude.json, and on claude v2.1.217 that does not reproduce the modal. On the
// REMOTE path the isolation was originally missing: the
// worker's claude read the worker's SHARED ~/.claude.json, whose modal-dismissing
// state can be perturbed by concurrent processes / theme/trust read-modify-writes,
// so claude wedged on the modal BEFORE the SessionStart hook fired → agent_ready
// never dialed back → deterministic agent_ready_timeout (the hk-qxvc2 stall;
// claude-only + remote-only). Isolating the config on the worker too closes it
// (and the fresh-worker case, hk-g5wkt).
//
// # Mechanism (mirrors EnsureWorktreeTrustVia)
//
// The preparation runs as a python3 program fed ON STDIN to `python3 - <worktree>`
// (NOT via -c — see EnsureWorktreeTrustVia for the SSH argv-resplit hazard), with
// the worktree path as the single argv token. On the worker the program:
//
//  1. mkdir -p <worktree>/.harmonik/claude-config (0o700).
//  2. Seeds <dir>/.claude.json by COPYING the WORKER's OWN ~/.claude.json (the
//     worker's onboarded config is the correct modal-dismisser for a process
//     running ON the worker — box A's config is irrelevant there). If that source
//     is missing/unreadable/corrupt, it falls back to a minimal onboarding-complete
//     config (firstStartTime only) — same best-effort fallback as the local path.
//  3. Upserts the worktree-trust entry
//     (projects[<realpath(worktree)>].hasTrustDialogAccepted = true) INTO the
//     isolated config, realpath-normalizing the key ON THE WORKER so it matches
//     claude's own realpath() of its cwd once the config is relocated.
//  4. Writes atomically (temp file + os.replace, 0o600).
//
// Unlike the shared ~/.claude.json writers this needs NO cross-process flock: the
// isolated dir is private to ONE worktree, so no other launch races it.
//
// The returned worker-absolute path is computed in Go from the worker-absolute
// workspacePath (filepath.Join, same as the local variant and the other *Via
// path builders) — the program does not echo it back. On the seed program's
// failure the error is propagated so the caller does NOT exec claude (an
// un-isolated launch re-wedges on the modal), mirroring the local fatal posture.
func PrepareIsolatedClaudeConfigDirVia(ctx context.Context, runner tmux.CommandRunner, workspacePath string) (string, error) {
	if runner == nil {
		return PrepareIsolatedClaudeConfigDir(workspacePath)
	}

	cmd := runner.Command(ctx, "python3", "-", workspacePath)
	cmd.Stdin = bytes.NewReader([]byte(workerIsolatedConfigProgram))
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("workspace: PrepareIsolatedClaudeConfigDirVia %s: %w\nremote: %s", workspacePath, err, out)
	}
	return filepath.Join(workspacePath, ".harmonik", isolatedClaudeConfigDirName), nil
}

var workerIsolatedConfigProgram = fmt.Sprintf(`
import json, os, sys, tempfile
arg = sys.argv[1]
if len(arg) >= 2 and arg[0] == "'" and arg[-1] == "'":
    arg = arg[1:-1]
config_dir = os.path.join(arg, ".harmonik", "claude-config")
os.makedirs(config_dir, mode=0o700, exist_ok=True)
try:
    os.chmod(config_dir, 0o700)
except OSError:
    pass
dest = os.path.join(config_dir, ".claude.json")
src = os.path.join(os.path.expanduser("~"), ".claude.json")

def load_src():
    try:
        with open(src) as f:
            cfg = json.load(f)
    except (FileNotFoundError, ValueError, OSError):
        return None
    return cfg if isinstance(cfg, dict) else None

cfg = load_src()
if cfg is None:
    cfg = {"firstStartTime": %q}

wt = os.path.realpath(arg)
projects = cfg.get("projects")
if not isinstance(projects, dict):
    projects = {}
    cfg["projects"] = projects
entry = projects.get(wt)
if not isinstance(entry, dict):
    entry = {}
    projects[wt] = entry
entry["hasTrustDialogAccepted"] = True

d = os.path.dirname(dest) or "."
fd, tmp = tempfile.mkstemp(dir=d, prefix=".claude.json.tmp-")
try:
    os.fchmod(fd, 0o600)
    with os.fdopen(fd, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")
    os.replace(tmp, dest)
except BaseException:
    try:
        os.unlink(tmp)
    except OSError:
        pass
    raise
`, fallbackFirstStartTime)
