package workspace

import (
	"strings"
	"testing"
)

// TestWM004_WorkspaceIDFromRunID locks the deterministic workspace_id derivation
// required by workspace-model.md §4.1 WM-004:
//
//	workspace_id = "ws-" + run_id
//
// Spec ref: workspace-model.md §4.1 WM-004 — "The workspace_id MUST be
// generated by the deterministic construction workspace_id = "ws-" + run_id
// so that a daemon restart finds the same workspace_id for a given run without
// consulting a separate store."
func TestWM004_WorkspaceIDFromRunID(t *testing.T) {
	t.Parallel()

	t.Run("derivation-matches-ws-prefix-plus-run-id", func(t *testing.T) {
		t.Parallel()

		cases := []struct {
			runID           string
			wantWorkspaceID string
		}{
			{
				runID:           "0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0002",
				wantWorkspaceID: "ws-0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0002",
			},
			{
				runID:           "0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0003",
				wantWorkspaceID: "ws-0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0003",
			},
			{
				runID:           "abcdef01-2345-7000-8abc-def012345678",
				wantWorkspaceID: "ws-abcdef01-2345-7000-8abc-def012345678",
			},
		}

		for _, tc := range cases {
			t.Run(tc.runID, func(t *testing.T) {
				t.Parallel()

				got := WorkspaceIDFromRunID(tc.runID)
				if got != tc.wantWorkspaceID {
					t.Errorf("WM-004: WorkspaceIDFromRunID(%q) = %q, want %q",
						tc.runID, got, tc.wantWorkspaceID)
				}
			})
		}
	})

	t.Run("derivation-is-deterministic", func(t *testing.T) {
		t.Parallel()

		// The same run_id must always produce the same workspace_id (no randomness).
		runID := "0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0004"
		first := WorkspaceIDFromRunID(runID)
		second := WorkspaceIDFromRunID(runID)
		if first != second {
			t.Errorf("WM-004: WorkspaceIDFromRunID is non-deterministic: %q != %q", first, second)
		}
	})

	t.Run("workspace-id-starts-with-ws-prefix", func(t *testing.T) {
		t.Parallel()

		// WM-004: the prefix "ws-" is fixed; downstream MUST NOT parse it but it
		// must be present for the contract to hold.
		runID := "0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0005"
		got := WorkspaceIDFromRunID(runID)
		if !strings.HasPrefix(got, "ws-") {
			t.Errorf("WM-004: WorkspaceIDFromRunID(%q) = %q; want prefix %q", runID, got, "ws-")
		}
	})

	t.Run("run-id-embedded-in-workspace-id", func(t *testing.T) {
		t.Parallel()

		// The run_id portion is embedded after the "ws-" prefix — downstream
		// MUST NOT rely on this parsing, but the embedding is normative.
		runID := "0196a1b2-c3d4-7ef0-8a1b-2c3d4e5f0006"
		got := WorkspaceIDFromRunID(runID)
		if !strings.HasSuffix(got, runID) {
			t.Errorf("WM-004: WorkspaceIDFromRunID(%q) = %q; want run_id as suffix", runID, got)
		}
	})
}
