package scenario

import (
	"fmt"
	"os"
	"path/filepath"
)

// NewFixtureRoot creates a new per-suite ephemeral fixture root directory and
// returns its absolute path.
//
// If parentDir is empty, os.TempDir() is used as the parent (the OS-temp
// default per SH-016). Otherwise parentDir is used as the parent — this is
// the `--fixture-root <path>` override surface (§5 SH-032).
//
// The directory is named with a "harmonik-harness-" prefix followed by a
// unique random suffix generated by the OS so that successive suite
// invocations produce distinct directories. Prior fixture roots accumulate
// under parentDir until deleted by the operator (`harmonik harness clean` or
// `rm -rf`); this function MUST NOT clean them up.
//
// The returned path MUST be stored in SuiteResult.fixture_root and reported
// on the harness CLI surface per SH-016.
//
// Spec ref: specs/scenario-harness.md §4.4 SH-016.
func NewFixtureRoot(parentDir string) (string, error) {
	if parentDir == "" {
		parentDir = os.TempDir()
	}
	//nolint:gosec // G301: 0755 matches existing .harmonik dir conventions
	if err := os.MkdirAll(parentDir, 0o755); err != nil {
		return "", fmt.Errorf("fixture root: ensure parent dir %q: %w", parentDir, err)
	}
	dir, err := os.MkdirTemp(parentDir, "harmonik-harness-")
	if err != nil {
		return "", fmt.Errorf("fixture root: create ephemeral dir under %q: %w", parentDir, err)
	}
	return dir, nil
}

// ScenarioProjectRoot returns the absolute path of the per-scenario synthetic
// project root for the named scenario, rooted at the per-suite fixture root.
//
// The synthetic project root is where the harness places the per-scenario
// daemon's working directory; the daemon's startup sequence (PL-005) writes
// .harmonik/ artifacts relative to this path, keeping the operator's own
// .harmonik/ tree untouched per SH-014.
//
// scenarioName MUST be the scenario identifier as declared in the scenario file
// (or the matrix-expanded name per SH-030). The caller is responsible for
// ensuring uniqueness across scenarios in the suite (SH-005 name-uniqueness
// rule guarantees this when the names come from scenario YAML files).
//
// Spec ref: specs/scenario-harness.md §4.4 SH-016a.
func ScenarioProjectRoot(fixtureRoot, scenarioName string) string {
	return filepath.Join(fixtureRoot, scenarioName, "project")
}
