package core

import "github.com/google/uuid"

// agentevents_hqwn59.go — event-bus payload types for §8.3 agent/handler
// lifecycle events covered by this implementer wave (hqwn59b):
//   - agent_ready              (§8.3.1)
//   - agent_output_chunk       (§8.3.3)
//   - agent_failed             (§8.3.5)
//   - handler_capabilities     (§8.3.9)
//
// Spec ref: specs/event-model.md §8.3.
// Bead refs: hk-hqwn.59.21, hk-hqwn.59.23, hk-hqwn.59.25, hk-hqwn.59.29.

// AgentReadyPayload is the typed event payload for the agent_ready event
// (event-model.md §8.3.1).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle observability; the
// orchestrator uses this event to confirm the agent subprocess is ready to
// accept dispatch per handler-contract.md §4.1).
//
// Emitted by the handler subprocess via the daemon watcher when the agent
// process signals readiness. The session_id is UUIDv7 generated by the handler
// and opaque to non-handler consumers per §8.3 note and handler-contract.md §4.1.
//
// # Payload fields (event-model.md §8.3.1)
//
//   - run_id        — the run in whose context the agent is ready
//   - session_id    — handler-assigned session identifier (UUIDv7, opaque outside handler layer)
//   - capabilities  — list of capability strings advertised by this agent instance
type AgentReadyPayload struct {
	// RunID is the run in whose context the agent became ready.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// Capabilities is the list of capability strings advertised by this agent.
	// Required (non-nil; may be empty slice if no capabilities are declared).
	Capabilities []string `json:"capabilities"`
}

// Valid reports whether p is a well-formed AgentReadyPayload.
//
// Rules per event-model.md §8.3.1:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - Capabilities must be non-nil.
func (p AgentReadyPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.Capabilities == nil {
		return false
	}
	return true
}

// AgentOutputChunkPayload is the typed event payload for the agent_output_chunk
// event (event-model.md §8.3.3).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: L (lossy-tail-ok — per-chunk statistical aggregate; the
// improvement-loop subsystem requires per-chunk cost attribution but tolerated
// loss per §8.9 granularity note and EV-017/EV-INV-002).
//
// Emitted by the handler subprocess via the daemon watcher for each output
// chunk. chunk_index is monotonically increasing within a session and allows
// consumers to detect drops.
//
// # Payload fields (event-model.md §8.3.3 §6.3)
//
//   - run_id       — the run in whose context the chunk was emitted
//   - session_id   — handler-assigned session identifier
//   - chunk_index  — monotonic zero-based chunk counter within this session
//   - bytes_emitted — number of bytes in this chunk
//   - chunk_digest — optional content-addressable digest of this chunk (SHA-256 hex)
type AgentOutputChunkPayload struct {
	// RunID is the run in whose context the chunk was emitted.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// ChunkIndex is the zero-based monotonic chunk counter within this session.
	// Required (must be >= 0).
	ChunkIndex int `json:"chunk_index"`

	// BytesEmitted is the number of bytes in this chunk. Required (must be >= 0).
	BytesEmitted int `json:"bytes_emitted"`

	// ChunkDigest is an optional SHA-256 hex digest of the chunk content.
	// Corresponds to chunk_digest? in §8.3.3 §6.3. Nil when not provided.
	// Non-nil must be non-empty.
	ChunkDigest *string `json:"chunk_digest,omitempty"`
}

// Valid reports whether p is a well-formed AgentOutputChunkPayload.
//
// Rules per event-model.md §8.3.3 §6.3:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - ChunkIndex must be >= 0.
//   - BytesEmitted must be >= 0.
//   - ChunkDigest, when non-nil, must be non-empty.
func (p AgentOutputChunkPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.ChunkIndex < 0 {
		return false
	}
	if p.BytesEmitted < 0 {
		return false
	}
	if p.ChunkDigest != nil && *p.ChunkDigest == "" {
		return false
	}
	return true
}

// AgentFailedPayload is the typed event payload for the agent_failed event
// (event-model.md §8.3.5).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle observability; the
// orchestrator and reconciliation subsystem consume this to classify the
// failure and decide on restart or escalation).
//
// Emitted by the daemon watcher when the handler subprocess exits with an
// error or crashes. error_category carries the typed sentinel class per
// handler-contract.md §4.5.
//
// # Payload fields (event-model.md §8.3.5)
//
//   - run_id         — the run in whose context the agent failed
//   - session_id     — handler-assigned session identifier
//   - ended_at       — RFC 3339 wall-clock timestamp at failure detection
//   - error_category — typed failure class (per handler-contract.md §4.5)
//   - reason         — human-readable failure reason string (for diagnosis)
type AgentFailedPayload struct {
	// RunID is the run in whose context the agent failed.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// EndedAt is the RFC 3339 wall-clock timestamp at which the failure was
	// detected. Required (non-empty).
	EndedAt string `json:"ended_at"`

	// ErrorCategory is the typed failure class per handler-contract.md §4.5.
	// Required; must be a valid ErrorCategory constant.
	ErrorCategory ErrorCategory `json:"error_category"`

	// Reason is a human-readable failure reason string for operator diagnosis.
	// Required (non-empty).
	Reason string `json:"reason"`
}

// Valid reports whether p is a well-formed AgentFailedPayload.
//
// Rules per event-model.md §8.3.5:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - EndedAt must be non-empty.
//   - ErrorCategory must be a valid ErrorCategory constant.
//   - Reason must be non-empty.
func (p AgentFailedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.EndedAt == "" {
		return false
	}
	if !p.ErrorCategory.Valid() {
		return false
	}
	if p.Reason == "" {
		return false
	}
	return true
}

// HandlerCapabilitiesPayload is the typed event payload for the
// handler_capabilities event (event-model.md §8.3.9).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — version-negotiation observability; the
// orchestrator uses this event to confirm protocol version compatibility per
// handler-contract.md §4.1 §8.1.10).
//
// Emitted by the handler subprocess via the daemon watcher as the first
// message of the handler session, advertising supported protocol versions.
// The orchestrator uses this for version negotiation per handler-contract.md §8.1.10.
//
// # Payload fields (event-model.md §8.3.9)
//
//   - run_id                    — the run in whose context the handler reported capabilities
//   - session_id                — handler-assigned session identifier
//   - protocol_versions_supported — list of handler-contract protocol version strings this handler supports
type HandlerCapabilitiesPayload struct {
	// RunID is the run in whose context the handler reported capabilities.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// ProtocolVersionsSupported is the list of protocol version strings supported
	// by this handler. Required (non-nil; must be non-empty to be meaningful
	// for version negotiation per handler-contract.md §8.1.10).
	ProtocolVersionsSupported []string `json:"protocol_versions_supported"`
}

// Valid reports whether p is a well-formed HandlerCapabilitiesPayload.
//
// Rules per event-model.md §8.3.9:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - ProtocolVersionsSupported must be non-nil and non-empty.
func (p HandlerCapabilitiesPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if len(p.ProtocolVersionsSupported) == 0 {
		return false
	}
	return true
}
