package core

import "github.com/google/uuid"

// agentevents_hqwn59.go — event-bus payload types for §8.3 agent/handler
// lifecycle events covered by this implementer wave (hqwn59b):
//   - agent_started            (§8.3.2)
//   - agent_ready              (§8.3.1)
//   - agent_output_chunk       (§8.3.3)
//   - agent_failed             (§8.3.5)
//   - agent_rate_limit_status  (§8.3.6)
//   - skills_provisioned       (§8.3.8)
//   - handler_capabilities     (§8.3.9)
//
// Spec ref: specs/event-model.md §8.3.
// Bead refs: hk-hqwn.59.22, hk-hqwn.59.21, hk-hqwn.59.23, hk-hqwn.59.25, hk-hqwn.59.26, hk-hqwn.59.28, hk-hqwn.59.29.

// AgentStartedPayload is the typed event payload for the agent_started event
// (event-model.md §8.3.2).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle audit and observability; the
// orchestrator and audit subsystem use this event to record that an agent
// subprocess was dispatched and began execution per handler-contract.md §4.1).
//
// Emitted by the handler subprocess via the daemon watcher immediately after the
// handler begins execution. The event_id is stamped by the daemon watcher per
// EV-002b; the handler does not generate event_id independently.
//
// # Payload fields (event-model.md §8.3.2)
//
//   - run_id      — the run in whose context the agent started
//   - session_id  — handler-assigned session identifier (UUIDv7, opaque outside handler layer)
//   - node_id     — the workflow node that this agent instance is executing
//   - agent_type  — the conformance class of the handler subprocess (AR-025)
//   - started_at  — RFC 3339 wall-clock timestamp at which the agent process started
//
// Note: agent_started MUST NOT include environment variables per HC-029
// (handler-contract.md §6.4). See hk-8i31.36 and specaudit HC-029 binding test.
type AgentStartedPayload struct {
	// RunID is the run in whose context the agent started.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// NodeID is the workflow node that this agent instance is executing.
	// Required (non-empty).
	NodeID NodeID `json:"node_id"`

	// AgentType is the conformance class of the handler subprocess.
	// Required; must satisfy AgentType.Valid() per AR-025 / AR-027.
	AgentType AgentType `json:"agent_type"`

	// StartedAt is the RFC 3339 wall-clock timestamp at which the agent process
	// started. Required (non-empty).
	StartedAt string `json:"started_at"`
}

// Valid reports whether p is a well-formed AgentStartedPayload.
//
// Rules per event-model.md §8.3.2:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - NodeID must be non-empty.
//   - AgentType must satisfy AgentType.Valid().
//   - StartedAt must be non-empty.
func (p AgentStartedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.NodeID == "" {
		return false
	}
	if !p.AgentType.Valid() {
		return false
	}
	if p.StartedAt == "" {
		return false
	}
	return true
}

// AgentReadyPayload is the typed event payload for the agent_ready event
// (event-model.md §8.3.1).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle observability; the
// orchestrator uses this event to confirm the agent subprocess is ready to
// accept dispatch per handler-contract.md §4.1).
//
// Emitted by the handler subprocess via the daemon watcher when the agent
// process signals readiness. The session_id is UUIDv7 generated by the handler
// and opaque to non-handler consumers per §8.3 note and handler-contract.md §4.1.
//
// # Payload fields (event-model.md §8.3.1)
//
//   - run_id        — the run in whose context the agent is ready
//   - session_id    — handler-assigned session identifier (UUIDv7, opaque outside handler layer)
//   - capabilities  — list of capability strings advertised by this agent instance
type AgentReadyPayload struct {
	// RunID is the run in whose context the agent became ready.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// Capabilities is the list of capability strings advertised by this agent.
	// Required (non-nil; may be empty slice if no capabilities are declared).
	Capabilities []string `json:"capabilities"`

	// ClaudeSessionID is the Claude Code session identifier that generated the
	// SessionStart hook event triggering this agent_ready synthesis. Only
	// populated when Provenance == "claude_session_start" (i.e. relay-synthesized
	// under the tmux substrate). Empty for conventional handler subprocess emission.
	// Added by hk-5cox8 to allow post-hoc correlation of which runs received
	// agent_ready and which did not.
	ClaudeSessionID string `json:"claude_session_id,omitempty"`

	// Provenance is the source of the agent_ready signal.  Set to
	// "claude_session_start" when the message was synthesized by the
	// hook-relay on first SessionStart receipt (CHB-013 / HC-039 under the
	// tmux substrate).  Empty for conventional handler subprocess emission.
	Provenance string `json:"provenance,omitempty"`
}

// Valid reports whether p is a well-formed AgentReadyPayload.
//
// Rules per event-model.md §8.3.1:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - Capabilities must be non-nil.
func (p AgentReadyPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.Capabilities == nil {
		return false
	}
	return true
}

// LaunchInitiatedPayload is the typed event payload for the launch_initiated
// event.
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=deterministic; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle observability).
//
// Emitted by the handler-process as the pre-exec precursor (CHB-018 step 4)
// under the interactive (tmux) substrate.  Signals that the handler is about
// to exec Claude Code but does NOT indicate ready-state.
//
// # Payload fields
//
//   - run_id            — the run in whose context the launch is occurring
//   - session_id        — handler-assigned session identifier
//   - claude_session_id — the Claude session ID minted or reused for this launch
//   - phase             — launch phase (e.g. "single", "implementer-initial")
type LaunchInitiatedPayload struct {
	// RunID is the run in whose context the launch is occurring.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	SessionID SessionID `json:"session_id"`

	// ClaudeSessionID is the Claude Code session identifier minted or reused
	// by the handler subprocess for this launch. Required (non-empty).
	ClaudeSessionID string `json:"claude_session_id"`

	// Phase is the launch phase string. Empty when unknown.
	Phase string `json:"phase,omitempty"`
}

// Valid reports whether p is a well-formed LaunchInitiatedPayload.
func (p LaunchInitiatedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.ClaudeSessionID == "" {
		return false
	}
	return true
}

// AgentReadyTimeoutPayload is the typed event payload for the agent_ready_timeout
// event (hk-5cox8 observability).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=deterministic; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — HC-056 timeout observability; lets post-hoc
// analysis distinguish "never ready" from "ready but not logged").
//
// Emitted by the daemon workloop when the HC-056 agent_ready timeout fires —
// i.e. no agent_ready relay message arrived within the configured deadline.
//
// # Payload fields
//
//   - run_id            — the run in whose context the timeout fired
//   - claude_session_id — the Claude session ID targeted by this run
//   - timeout_ms        — the effective timeout in milliseconds (default 30000)
//
// Refs: hk-5cox8.
type AgentReadyTimeoutPayload struct {
	// RunID is the run in whose context the timeout fired.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// ClaudeSessionID is the Claude Code session identifier that was expected
	// to emit agent_ready but did not within the timeout window.
	// Required (non-empty).
	ClaudeSessionID string `json:"claude_session_id"`

	// TimeoutMs is the effective HC-056 timeout in milliseconds.
	// Required (positive).
	TimeoutMs int64 `json:"timeout_ms"`
}

// Valid reports whether p is a well-formed AgentReadyTimeoutPayload.
func (p AgentReadyTimeoutPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.ClaudeSessionID == "" {
		return false
	}
	if p.TimeoutMs <= 0 {
		return false
	}
	return true
}

// AgentOutputChunkPayload is the typed event payload for the agent_output_chunk
// event (event-model.md §8.3.3).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: L (lossy-tail-ok — per-chunk statistical aggregate; the
// improvement-loop subsystem requires per-chunk cost attribution but tolerated
// loss per §8.9 granularity note and EV-017/EV-INV-002).
//
// Emitted by the handler subprocess via the daemon watcher for each output
// chunk. chunk_index is monotonically increasing within a session and allows
// consumers to detect drops.
//
// # Payload fields (event-model.md §8.3.3 §6.3)
//
//   - run_id       — the run in whose context the chunk was emitted
//   - session_id   — handler-assigned session identifier
//   - chunk_index  — monotonic zero-based chunk counter within this session
//   - bytes_emitted — number of bytes in this chunk
//   - chunk_digest — optional content-addressable digest of this chunk (SHA-256 hex)
type AgentOutputChunkPayload struct {
	// RunID is the run in whose context the chunk was emitted.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// ChunkIndex is the zero-based monotonic chunk counter within this session.
	// Required (must be >= 0).
	ChunkIndex int `json:"chunk_index"`

	// BytesEmitted is the number of bytes in this chunk. Required (must be >= 0).
	BytesEmitted int `json:"bytes_emitted"`

	// ChunkDigest is an optional SHA-256 hex digest of the chunk content.
	// Corresponds to chunk_digest? in §8.3.3 §6.3. Nil when not provided.
	// Non-nil must be non-empty.
	ChunkDigest *string `json:"chunk_digest,omitempty"`
}

// Valid reports whether p is a well-formed AgentOutputChunkPayload.
//
// Rules per event-model.md §8.3.3 §6.3:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - ChunkIndex must be >= 0.
//   - BytesEmitted must be >= 0.
//   - ChunkDigest, when non-nil, must be non-empty.
func (p AgentOutputChunkPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.ChunkIndex < 0 {
		return false
	}
	if p.BytesEmitted < 0 {
		return false
	}
	if p.ChunkDigest != nil && *p.ChunkDigest == "" {
		return false
	}
	return true
}

// AgentFailedPayload is the typed event payload for the agent_failed event
// (event-model.md §8.3.5).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — handler lifecycle observability; the
// orchestrator and reconciliation subsystem consume this to classify the
// failure and decide on restart or escalation).
//
// Emitted by the daemon watcher when the handler subprocess exits with an
// error or crashes. error_category carries the typed sentinel class per
// handler-contract.md §4.5.
//
// # Payload fields (event-model.md §8.3.5)
//
//   - run_id         — the run in whose context the agent failed
//   - session_id     — handler-assigned session identifier
//   - ended_at       — RFC 3339 wall-clock timestamp at failure detection
//   - error_category — typed failure class (per handler-contract.md §4.5)
//   - reason         — human-readable failure reason string (for diagnosis)
type AgentFailedPayload struct {
	// RunID is the run in whose context the agent failed.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// EndedAt is the RFC 3339 wall-clock timestamp at which the failure was
	// detected. Required (non-empty).
	EndedAt string `json:"ended_at"`

	// ErrorCategory is the typed failure class per handler-contract.md §4.5.
	// Required; must be a valid ErrorCategory constant.
	ErrorCategory ErrorCategory `json:"error_category"`

	// Reason is a human-readable failure reason string for operator diagnosis.
	// Required (non-empty).
	Reason string `json:"reason"`
}

// Valid reports whether p is a well-formed AgentFailedPayload.
//
// Rules per event-model.md §8.3.5:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - EndedAt must be non-empty.
//   - ErrorCategory must be a valid ErrorCategory constant.
//   - Reason must be non-empty.
func (p AgentFailedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.EndedAt == "" {
		return false
	}
	if !p.ErrorCategory.Valid() {
		return false
	}
	if p.Reason == "" {
		return false
	}
	return true
}

// AgentRateLimitStatus is the typed discriminator for the status field of an
// agent_rate_limit_status event (event-model.md §8.3.6 §6.3).
//
// This is a paired-phase lifecycle type per §8.9(h): emitters MUST emit only
// on status transitions; successive emissions with identical status for the
// same session are forbidden. The changed_at field MUST carry millisecond
// resolution per §8.9(h).
type AgentRateLimitStatus string

const (
	// AgentRateLimitStatusActive indicates a rate limit is currently in effect.
	AgentRateLimitStatusActive AgentRateLimitStatus = "active"

	// AgentRateLimitStatusCleared indicates a previously active rate limit has cleared.
	AgentRateLimitStatusCleared AgentRateLimitStatus = "cleared"
)

// Valid reports whether s is one of the two declared AgentRateLimitStatus constants.
func (s AgentRateLimitStatus) Valid() bool {
	switch s {
	case AgentRateLimitStatusActive, AgentRateLimitStatusCleared:
		return true
	default:
		return false
	}
}

// AgentRateLimitStatusPayload is the typed event payload for the
// agent_rate_limit_status event (event-model.md §8.3.6 §6.3).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — rate-limit lifecycle observability; the
// orchestrator uses this event to track when rate-limiting is active and when
// it has cleared, enabling dispatch throttling per §8.3.6 §8.9(h)).
//
// Emitted by the handler subprocess via the daemon watcher on rate-limit
// transitions. This is a paired-phase lifecycle event (§8.9(h)); emitters
// MUST emit only on transitions. rate_limit_source and retry_after_seconds
// are null when status=cleared.
//
// # Payload fields (event-model.md §8.3.6 §6.3)
//
//   - run_id              — the run in whose context the rate limit applies
//   - session_id          — handler-assigned session identifier
//   - status              — rate-limit phase (active / cleared)
//   - rate_limit_source   — optional provider-reported source of the rate limit
//   - retry_after_seconds — optional provider-reported retry delay in seconds
//   - changed_at          — RFC 3339 wall-clock timestamp at this phase transition (millisecond resolution)
type AgentRateLimitStatusPayload struct {
	// RunID is the run in whose context the rate limit applies.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// Status is the rate-limit phase at this transition. Required; must be a valid
	// AgentRateLimitStatus constant. Emitters MUST emit only on transitions per §8.9(h).
	Status AgentRateLimitStatus `json:"status"`

	// RateLimitSource is the optional provider-reported source identifying
	// which rate limit was hit (e.g., RateLimitSourceAnthropic). Nil when not
	// reported or when status=cleared. Non-nil must be a valid RateLimitSource
	// per the ^[a-z][a-z0-9-]*$ shape declared in ratelimitsource.go.
	// The vocabulary is open per event-model.md §6.3; known providers are
	// declared as constants in ratelimitsource.go.
	RateLimitSource *RateLimitSource `json:"rate_limit_source,omitempty"`

	// RetryAfterSeconds is the optional provider-reported retry delay. Nil when
	// not reported or when status=cleared. Non-nil must be >= 0.
	RetryAfterSeconds *int `json:"retry_after_seconds,omitempty"`

	// ChangedAt is the RFC 3339 wall-clock timestamp at this phase transition.
	// Required (non-empty). MUST carry millisecond resolution per §8.9(h).
	ChangedAt string `json:"changed_at"`
}

// Valid reports whether p is a well-formed AgentRateLimitStatusPayload.
//
// Rules per event-model.md §8.3.6 §6.3:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - Status must be a valid AgentRateLimitStatus constant.
//   - RateLimitSource, when non-nil, must satisfy RateLimitSource.Valid().
//   - RetryAfterSeconds, when non-nil, must be >= 0.
//   - ChangedAt must be non-empty.
func (p AgentRateLimitStatusPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if !p.Status.Valid() {
		return false
	}
	if p.RateLimitSource != nil && !p.RateLimitSource.Valid() {
		return false
	}
	if p.RetryAfterSeconds != nil && *p.RetryAfterSeconds < 0 {
		return false
	}
	if p.ChangedAt == "" {
		return false
	}
	return true
}

// ProvisionedSkill is the per-skill element in the skills[] list of a
// skills_provisioned event (event-model.md §8.3.8).
//
// Each element describes one skill injected into the agent session.
type ProvisionedSkill struct {
	// Name is the skill identifier as declared in the agent's skill registry.
	// Required (non-empty).
	Name string `json:"name"`

	// SourcePath is the filesystem path from which the skill was loaded.
	// Required (non-empty).
	SourcePath string `json:"source_path"`

	// Version is the optional version string for this skill. Nil when the skill
	// source does not declare a version.
	// TODO(hk-tyjfi): promote to typed SkillVersion alias when the skill
	// versioning scheme is formalized per §8.3.8.
	Version *string `json:"version,omitempty"`
}

// SkillsProvisionedPayload is the typed event payload for the skills_provisioned
// event (event-model.md §8.3.8).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — skill-injection audit and observability; the
// audit subsystem uses this event to record which skills were active during a
// session, enabling policy-compliance verification per §8.3.8).
//
// Emitted by the handler subprocess via the daemon watcher immediately before
// agent_ready, advertising the effective set of skills injected into the agent
// session per handler-contract.md §4.1 and hk-8i31.58.
//
// # Payload fields (event-model.md §8.3.8)
//
//   - run_id     — the run in whose context the skills were provisioned
//   - session_id — handler-assigned session identifier
//   - skills     — list of provisioned skill descriptors (each: name, source_path, version?)
type SkillsProvisionedPayload struct {
	// RunID is the run in whose context the skills were provisioned.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// Skills is the list of provisioned skill descriptors. Required (non-nil;
	// may be empty slice when no skills are injected).
	Skills []ProvisionedSkill `json:"skills"`
}

// Valid reports whether p is a well-formed SkillsProvisionedPayload.
//
// Rules per event-model.md §8.3.8:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - Skills must be non-nil.
//   - Each skill's Name must be non-empty.
//   - Each skill's SourcePath must be non-empty.
//   - Each skill's Version, when non-nil, must be non-empty.
func (p SkillsProvisionedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.Skills == nil {
		return false
	}
	for _, s := range p.Skills {
		if s.Name == "" {
			return false
		}
		if s.SourcePath == "" {
			return false
		}
		if s.Version != nil && *s.Version == "" {
			return false
		}
	}
	return true
}

// SessionLogLocationPayload is the typed event payload for the
// session_log_location event (event-model.md §8.3.7).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — session-log-pipeline audit; the audit subsystem
// uses this event to join handler-written session logs to the CASS index per
// workspace-model.md §4.7).
//
// Emitted by the handler subprocess via the daemon watcher early in the session
// (after handler_capabilities, before skills_provisioned/agent_ready). The
// session-log directory pre-exists at emission time; this event announces its
// path per handler-contract.md §4.2.HC-010.
//
// # Payload fields (event-model.md §8.3.7)
//
//   - run_id      — the run in whose context the session log is located
//   - session_id  — handler-assigned session identifier (UUIDv7, opaque outside handler layer)
//   - node_id     — the workflow node that this agent instance is executing
//   - agent_type  — the conformance class of the handler subprocess (AR-025)
//   - log_path    — absolute filesystem path to the session-log directory
//   - log_format  — log format identifier string
//   - bead_id     — optional bead identifier when the run is bead-tied (EM-014)
type SessionLogLocationPayload struct {
	// RunID is the run in whose context the session log is located.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// NodeID is the workflow node that this agent instance is executing.
	// Required (non-empty).
	NodeID NodeID `json:"node_id"`

	// AgentType is the conformance class of the handler subprocess.
	// Required; must satisfy AgentType.Valid() per AR-025 / AR-027.
	AgentType AgentType `json:"agent_type"`

	// LogPath is the absolute filesystem path to the session-log directory
	// pre-created by the workspace manager per workspace-model.md §4.7.
	// Required (non-empty).
	LogPath string `json:"log_path"`

	// LogFormat is the log format identifier string for this session log.
	// Required (non-empty).
	// TODO(hk-hqwn.59.27): promote to a typed LogFormat alias when the
	// log-format vocabulary is enumerated per event-model.md §8.3.7 and
	// workspace-model.md §4.7.
	LogFormat string `json:"log_format"`

	// BeadID is the optional bead identifier when the run is bead-tied per
	// execution-model.md §4.3.EM-014. Nil when the run has no bead tie.
	// Non-nil must be non-empty.
	BeadID *BeadID `json:"bead_id,omitempty"`
}

// Valid reports whether p is a well-formed SessionLogLocationPayload.
//
// Rules per event-model.md §8.3.7:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - NodeID must be non-empty.
//   - AgentType must satisfy AgentType.Valid().
//   - LogPath must be non-empty.
//   - LogFormat must be non-empty.
//   - BeadID, when non-nil, must dereference to a non-empty value.
func (p SessionLogLocationPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.NodeID == "" {
		return false
	}
	if !p.AgentType.Valid() {
		return false
	}
	if p.LogPath == "" {
		return false
	}
	if p.LogFormat == "" {
		return false
	}
	if p.BeadID != nil && *p.BeadID == "" {
		return false
	}
	return true
}

// HandlerCapabilitiesPayload is the typed event payload for the
// handler_capabilities event (event-model.md §8.3.9).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=idempotent
// Durability class: O (ordinary — version-negotiation observability; the
// orchestrator uses this event to confirm protocol version compatibility per
// handler-contract.md §4.1 §8.1.10).
//
// Emitted by the handler subprocess via the daemon watcher as the first
// message of the handler session, advertising supported protocol versions.
// The orchestrator uses this for version negotiation per handler-contract.md §8.1.10.
//
// # Payload fields (event-model.md §8.3.9)
//
//   - run_id                    — the run in whose context the handler reported capabilities
//   - session_id                — handler-assigned session identifier
//   - protocol_versions_supported — list of handler-contract protocol version strings this handler supports
type HandlerCapabilitiesPayload struct {
	// RunID is the run in whose context the handler reported capabilities.
	// Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler-assigned session identifier. Required (non-empty).
	// UUIDv7 per handler-contract.md §4.1; opaque to non-handler consumers.
	SessionID SessionID `json:"session_id"`

	// ProtocolVersionsSupported is the list of protocol version strings supported
	// by this handler. Required (non-nil; must be non-empty to be meaningful
	// for version negotiation per handler-contract.md §8.1.10).
	ProtocolVersionsSupported []string `json:"protocol_versions_supported"`
}

// Valid reports whether p is a well-formed HandlerCapabilitiesPayload.
//
// Rules per event-model.md §8.3.9:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty.
//   - ProtocolVersionsSupported must be non-nil and non-empty.
func (p HandlerCapabilitiesPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if len(p.ProtocolVersionsSupported) == 0 {
		return false
	}
	return true
}
