package core

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Event is the common envelope record every event carries (event-model.md §6.1).
//
// Every event emitted to the bus or appended to JSONL MUST carry these fields per
// EV-001. The envelope is type-discriminated: the payload bytes are decoded by the
// per-type registry keyed on Type per §6.3.
//
// Type uses string directly. The EventType enum (~79 rows) is owned by the parent
// bead hk-hqwn.59 and is too large to define here. The hoist to EventType is
// non-breaking once the enum lands.
type Event struct {
	// EventID is the unique identifier for this event (EV-002).
	// MUST be a UUIDv7 generated by the daemon's monotonic generator per EV-002
	// and EV-002b. Monotonic non-decrease within a process is enforced per EV-002a.
	// Required (non-nil UUID).
	EventID EventID

	// SchemaVersion is the envelope schema version. Bump on envelope-level changes
	// per EV-028. Non-zero; the per-type registry independently tracks per-payload
	// versions. "N-1 readable" applies per EV-029.
	SchemaVersion int

	// Type identifies the event type; MUST be one of the §8 rows (event-model.md §8).
	// The EventType enum is declared in a separate bead (hk-hqwn.59); this field
	// uses string until that enum lands (non-breaking hoist).
	// Required (non-empty).
	Type string

	// TimestampWall is the RFC 3339 wall-clock time at the emitter (EV-001).
	// The emitter MUST perform exactly one wall-clock read per emission and reuse
	// that reading for both TimestampWall and UUIDv7 generation so the envelope is
	// self-consistent.
	// Required (non-zero).
	TimestampWall time.Time

	// TimestampMonoNsec is the optional monotonic nanoseconds from the emitter's
	// process clock (event-model.md §6.1 EV-001, EV-003). Process-scoped; not
	// meaningful across process restarts. When non-nil must be > 0.
	TimestampMonoNsec *int64

	// RunID is present when the event is scoped to a run (EV-001).
	// Optional; when non-nil must not be uuid.Nil.
	RunID *RunID

	// StateID is present when the event is scoped to a run-state (EV-001).
	// Optional; when non-nil must not be uuid.Nil.
	StateID *StateID

	// SourceSubsystem is the Go-package-identifier string of the emitting subsystem
	// per EV-004 and architecture.md §4.5. Required (non-empty).
	SourceSubsystem string

	// TraceContext carries optional cross-subsystem correlation identifiers (§6.1).
	// Optional; when non-nil must satisfy TraceContext.Valid().
	TraceContext *TraceContext

	// Payload is the type-specific event body as raw JSON bytes (json.RawMessage).
	// Decoded by the per-type registry keyed on Type per §6.3.
	// Required (non-nil). A zero-length (but non-nil) json.RawMessage is valid for
	// event types that carry no body (e.g., a heartbeat); decoding is the consumer's
	// responsibility.
	Payload json.RawMessage
}

// Valid reports whether all required fields carry non-zero values and all
// optional pointer fields, when non-nil, satisfy their structural constraints.
//
// Rules:
//   - EventID is not uuid.Nil
//   - SchemaVersion is not zero
//   - Type is non-empty (enum validation is a consumer concern; the enum does not exist yet)
//   - TimestampWall is not the zero Time
//   - TimestampMonoNsec, when non-nil, must be > 0
//   - RunID, when non-nil, must dereference to a non-uuid.Nil RunID
//   - StateID, when non-nil, must dereference to a non-uuid.Nil StateID
//   - SourceSubsystem is non-empty
//   - TraceContext, when non-nil, must satisfy TraceContext.Valid()
//   - Payload is non-nil (zero-length is permitted for no-body event types)
func (e Event) Valid() bool {
	if uuid.UUID(e.EventID) == uuid.Nil {
		return false
	}
	if e.SchemaVersion == 0 {
		return false
	}
	if e.Type == "" {
		return false
	}
	if e.TimestampWall.IsZero() {
		return false
	}
	if e.TimestampMonoNsec != nil && *e.TimestampMonoNsec <= 0 {
		return false
	}
	if e.RunID != nil && uuid.UUID(*e.RunID) == uuid.Nil {
		return false
	}
	if e.StateID != nil && uuid.UUID(*e.StateID) == uuid.Nil {
		return false
	}
	if e.SourceSubsystem == "" {
		return false
	}
	if e.TraceContext != nil && !e.TraceContext.Valid() {
		return false
	}
	if e.Payload == nil {
		return false
	}
	return true
}
