package core

import "github.com/google/uuid"

// OutcomeEmittedPayload is the typed event payload for the outcome_emitted event
// (event-model.md §8.1.8; handler-contract.md §4.1 HC-008).
//
// Tags: mechanism
// Axes: llm-freedom=none; io-determinism=best-effort; replay-safety=safe; idempotency=non-idempotent
// Durability class: O (ordinary — emitted via daemon watcher as the handler
// subprocess produces an outcome; best-effort delivery is adequate since the
// authoritative outcome lives in the handler output file on the workspace branch).
//
// # Spec source (event-model.md §8.1.8)
//
// Emitted by the handler (via daemon watcher) when the handler subprocess
// writes an Outcome record (handler-contract.md §4.1 HC-008). The daemon
// watcher intercepts the handler output and emits this event on the bus.
// Source_subsystem will be the daemon-watcher's package identifier; the handler
// writes the raw outcome data that the watcher interprets.
//
// # Payload fields (event-model.md §8.1.8)
//
//   - run_id              — the run that produced this outcome (required)
//   - session_id          — the handler session identifier (UUIDv7 per HC §4.1; required)
//   - node_id             — the workflow node that produced the outcome (required)
//   - outcome_status      — the OutcomeStatus per execution-model.md §4.1.EM-005 (required)
//   - preferred_label     — the handler's preferred next-node label; absent when
//     the handler does not hint at a next-node preference
//   - suggested_next_ids  — the handler's suggested next-node IDs; absent when
//     no suggestion is provided; typed as []string (TODO: hoist to []NodeID
//     follow-up when NodeID alias is uniform across the handler-contract boundary)
type OutcomeEmittedPayload struct {
	// RunID is the run that produced this outcome. Required (must not be uuid.Nil).
	RunID RunID `json:"run_id"`

	// SessionID is the handler session identifier (handler-contract.md §4.1;
	// event-model.md §6.3 `agent_output_chunk` note on session_id typing).
	// UUIDv7 generated by the handler subprocess. Required (must not be uuid.Nil).
	SessionID SessionID `json:"session_id"`

	// NodeID is the workflow node that produced this outcome.
	// Required (non-empty).
	NodeID NodeID `json:"node_id"`

	// OutcomeStatus is the coarse result status per execution-model.md §4.1.EM-005.
	// Required (must be a valid OutcomeStatus constant).
	OutcomeStatus OutcomeStatus `json:"outcome_status"`

	// PreferredLabel is the handler's preferred outgoing edge label.
	// Corresponds to preferred_label? in event-model.md §8.1.8.
	// Nil when the handler does not hint at a preferred next-node.
	// Non-nil must be non-empty.
	//
	// TODO(hk-hqwn.59.8): type as *EdgeLabel once an EdgeLabel alias lands;
	// currently *string per the typed-alias-deferral pattern.
	PreferredLabel *string `json:"preferred_label,omitempty"`

	// SuggestedNextIDs is the handler's list of suggested next-node IDs.
	// Corresponds to suggested_next_ids? in event-model.md §8.1.8.
	// Nil (omitted) when the handler provides no suggestion.
	// Non-nil may be an empty slice (zero suggestions explicitly stated).
	//
	// TODO(hk-hqwn.59.8): type as []NodeID once the NodeID alias is confirmed
	// as the canonical cross-contract type; currently []string per the
	// typed-alias-deferral pattern.
	SuggestedNextIDs []string `json:"suggested_next_ids,omitempty"`
}

// Valid reports whether p is a well-formed OutcomeEmittedPayload.
//
// Rules per event-model.md §8.1.8:
//   - RunID must not be uuid.Nil.
//   - SessionID must be non-empty (UUIDv7 from the handler subprocess).
//   - NodeID must be non-empty.
//   - OutcomeStatus must be a valid declared constant.
//   - PreferredLabel, when non-nil, must be non-empty.
func (p OutcomeEmittedPayload) Valid() bool {
	if uuid.UUID(p.RunID) == uuid.Nil {
		return false
	}
	if p.SessionID == "" {
		return false
	}
	if p.NodeID == "" {
		return false
	}
	if !p.OutcomeStatus.Valid() {
		return false
	}
	if p.PreferredLabel != nil && *p.PreferredLabel == "" {
		return false
	}
	return true
}
