package core

// Reserved Run.context keys for workflow_mode = review-loop.
//
// When a Run carries workflow_mode = review-loop, its Context map MUST carry
// all four keys below at the times prescribed by execution-model.md §4.3 EM-012.
// Their absence in a review-loop run is an authoring error detected at claim time.
//
// For workflow_mode = single, no context keys are reserved by this spec.
// For workflow_mode = dot, reserved keys are out of scope for MVH conformance.
//
// Reference: execution-model.md §4.3 EM-012.
const (
	// RunContextKeyIterationCount is the 1-based count of implementer→reviewer
	// cycles the run has completed at a given moment (Integer, 1..3).
	// Initialized to 1 at claim time; incremented immediately before each
	// implementer dispatch after the first. MUST NOT exceed the cap defined by
	// §4.3.EM-015e (hardcoded 3 at MVH).
	//
	// Reference: execution-model.md §4.3 EM-012, §4.3.EM-015d, §4.3.EM-015e.
	RunContextKeyIterationCount = "iteration_count"

	// RunContextKeyLastVerdict holds the most recent reviewer verdict, one of
	// {APPROVE, REQUEST_CHANGES, BLOCK} per the agent-reviewer JSON schema v1,
	// or null before iteration 1's reviewer returns.
	//
	// Reference: execution-model.md §4.3 EM-012.
	RunContextKeyLastVerdict = "last_verdict"

	// RunContextKeyClaudeSessionID is the Claude Code session identifier captured
	// from the implementer's first launch (via `claude -p ... --output-format json`,
	// the JSON `session_id` field). Reused on subsequent implementer launches via
	// `claude --resume <claude_session_id>` so the implementer subprocess is fresh
	// per iteration but the Claude session is logically continuous.
	//
	// MUST NOT be conflated with harmonik's internal session_id event field
	// (a UUIDv7 generated by the handler per handler-contract.md §4.1):
	// claude_session_id is owned and minted by Claude Code; session_id is owned
	// and minted by the handler watcher.
	//
	// Reference: execution-model.md §4.3 EM-012, §4.3.EM-015d; §3 Glossary.
	RunContextKeyClaudeSessionID = "claude_session_id"

	// RunContextKeyLastDiffHash is the SHA-256 of `git diff <parent>..<head>`
	// output on the run's task branch at the end of the prior iteration. Used by
	// the no-progress early-exit detector: if the hash equals the prior
	// iteration's value (bit-identical diff against the parent), the daemon emits
	// no_progress_detected and terminates the run via the needs-attention close
	// path before launching the reviewer for the current iteration.
	//
	// Reference: execution-model.md §4.3 EM-012, §4.3.EM-015e.
	RunContextKeyLastDiffHash = "last_diff_hash"
)
