package main

// init_codex_block_hkyhvrh_test.go — `harmonik init` must scaffold the top-level
// codex: block so a freshly-initialised project can select the codex harness
// without its FIRST launch failing loud.
//
// The defect: writeConfigYAML composed keeper: + harnesses.pi: and NO codex: block.
// codex.stale_wal_max_bytes is REQUIRED with no compiled default
// (internal/daemon/codexwalguard.go), so the first codex-routed run in a fresh
// project died ~1s in at spec-build time with "required key
// `codex.stale_wal_max_bytes` is not set ... there is no compiled default".
//
// Cases:
//   - TestInitCodexBlock_GeneratedConfigSatisfiesRealWALGuard_HKYHVRH — the
//     LOAD-BEARING one. Writes config.yaml via the REAL writeConfigYAML, then feeds
//     it to the REAL guard through daemon.CodexHarness.LaunchSpec (the same call the
//     failing production path makes) and asserts the missing-key error is NOT
//     returned. A YAML-grep test would pass even if the key were scaffolded under
//     the wrong parent or with a type the parser rejects; this one would not.
//   - TestInitCodexBlock_KeyIsUncommentedUnderCodexParent_HKYHVRH — cheap structural
//     backstop: the key is emitted UNCOMMENTED and nested under a top-level `codex:`
//     parent (not under harnesses:, not under keeper:), with the 1048576 value.
//   - TestInitCodexBlock_ExampleIsTheOnlySourceOfTruth_HKYHVRH — the block
//     writeConfigYAML emits is byte-identical to codexConfigExampleYAML(), i.e. init
//     composes the shared template rather than carrying a second inline copy.
//
// Helper prefix: yhvrh
//
// Bead ref: hk-yhvrh.

import (
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gregberns/harmonik/internal/daemon"
	"github.com/gregberns/harmonik/internal/handlercontract"
)

// yhvrhInitConfig runs the REAL writeConfigYAML into a fresh temp project and
// returns (projectRoot, generatedBody).
//
// It deliberately does NOT re-compose the template the way writeConfigYAML does:
// pinning the production writer is the whole point. A helper that rebuilt
// `configYAMLContent + …ExampleYAML()` itself would stay green even if the codex
// block were deleted from writeConfigYAML — the exact hole this bead's test bar
// calls out.
func yhvrhInitConfig(t *testing.T) (string, string) {
	t.Helper()
	projectRoot := t.TempDir()
	if err := os.MkdirAll(filepath.Join(projectRoot, ".harmonik"), 0o755); err != nil {
		t.Fatalf("mkdir .harmonik: %v", err)
	}
	if rc := writeConfigYAML(projectRoot, "main", "hk", false, io.Discard, io.Discard); rc != 0 {
		t.Fatalf("writeConfigYAML returned %d, want 0", rc)
	}
	raw, err := os.ReadFile(filepath.Join(projectRoot, ".harmonik", "config.yaml"))
	if err != nil {
		t.Fatalf("read generated config.yaml: %v", err)
	}
	return projectRoot, string(raw)
}

// TestInitCodexBlock_GeneratedConfigSatisfiesRealWALGuard_HKYHVRH is the
// end-to-end round-trip: the config the real init path writes, parsed by the real
// stale-WAL guard, must not report the required key as missing.
//
// The guard is unexported; its only exported production entry point is
// CodexHarness.LaunchSpec, which calls cleanCodexStaleWAL FIRST (before
// buildCodexLaunchSpec) using os.Getwd() as the project root — hence the t.Chdir.
// LaunchSpec is expected to fail LATER (the billing guard finds no ChatGPT auth in
// a temp CODEX_HOME); the assertion is specifically that it does not fail with
// *daemon.ErrMissingCodexStaleWALMaxBytes.
//
// MUST NOT be made parallel: t.Chdir mutates process-wide cwd, and t.Chdir panics
// outright in a parallel test. Go parks every t.Parallel() test until the
// sequential top-level pass finishes, so a non-parallel test never overlaps with
// one — that property is what keeps the chdir safe here.
//
// CODEX_HOME is a t.TempDir, never the developer's real ~/.codex: the guard globs
// state_*.sqlite-wal under it and the billing guard writes config.toml into it.
func TestInitCodexBlock_GeneratedConfigSatisfiesRealWALGuard_HKYHVRH(t *testing.T) {
	projectRoot, _ := yhvrhInitConfig(t)

	// cleanCodexStaleWAL reads <cwd>/.harmonik/config.yaml.
	t.Chdir(projectRoot)

	// An isolated CODEX_HOME so the guard globs an empty directory and can never
	// touch the developer's real ~/.codex state WALs.
	codexHome := t.TempDir()
	harness := daemon.NewCodexHarness("codex", codexHome)

	_, err := harness.LaunchSpec(handlercontract.RunCtx{
		BeadID:        "hk-yhvrh",
		WorkspacePath: projectRoot,
	})

	var missing *daemon.ErrMissingCodexStaleWALMaxBytes
	if errors.As(err, &missing) {
		t.Errorf("want: the config.yaml generated by `harmonik init` resolves the "+
			"required codex.stale_wal_max_bytes key, so LaunchSpec does NOT return "+
			"ErrMissingCodexStaleWALMaxBytes; got that error: %v\n"+
			"regression shape: `harmonik init` stopped scaffolding the codex: block "+
			"(or scaffolded it under the wrong parent / with a type the guard's parser "+
			"rejects), so the FIRST codex launch in every fresh project fails loud at "+
			"spec-build time", err)
	}
}

// TestInitCodexBlock_KeyIsUncommentedUnderCodexParent_HKYHVRH asserts the
// structural shape of the scaffolded block: an uncommented top-level `codex:` key
// whose immediate child is stale_wal_max_bytes: 1048576.
func TestInitCodexBlock_KeyIsUncommentedUnderCodexParent_HKYHVRH(t *testing.T) {
	_, body := yhvrhInitConfig(t)

	parent := ""
	found := false
	for _, ln := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(ln)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if !strings.HasPrefix(ln, " ") {
			parent = trimmed // a top-level (column-0) key
			continue
		}
		if strings.HasPrefix(trimmed, "stale_wal_max_bytes:") {
			found = true
			if parent != "codex:" {
				t.Errorf("want: stale_wal_max_bytes nested under the top-level `codex:` parent "+
					"(that is the only path the guard's parser reads); got parent %q\n"+
					"regression shape: the key was scaffolded under the wrong block "+
					"(e.g. harnesses: or keeper:), which greps green but leaves the guard failing loud",
					parent)
			}
			if got, want := trimmed, "stale_wal_max_bytes: 1048576"; got != want {
				t.Errorf("want scaffolded line %q, got %q\n"+
					"regression shape: the suggested value drifted from the 1 MiB starting point "+
					"named in the guard's own error message", want, got)
			}
		}
	}
	if !found {
		t.Errorf("want: an UNCOMMENTED stale_wal_max_bytes line in the config.yaml `harmonik init` "+
			"generates; got none\nregression shape: init no longer scaffolds the codex: block, so "+
			"every fresh project's first codex launch fails loud\ngenerated config:\n%s", body)
	}
}

// TestInitCodexBlock_ExampleIsTheOnlySourceOfTruth_HKYHVRH asserts init composes
// the shared codexConfigExampleYAML() template verbatim rather than carrying its
// own inline copy that could drift from the guard's required-key set.
func TestInitCodexBlock_ExampleIsTheOnlySourceOfTruth_HKYHVRH(t *testing.T) {
	_, body := yhvrhInitConfig(t)

	example := codexConfigExampleYAML()
	if got, want := strings.Contains(body, example), true; got != want {
		t.Errorf("want: the generated config.yaml contains codexConfigExampleYAML() byte-for-byte "+
			"(one source of truth with the guard's required-key set); got contains=%v\n"+
			"regression shape: init inlined its own codex: YAML literal, which will silently drift "+
			"from internal/daemon's required keys\nexample block:\n%s\ngenerated config:\n%s",
			got, example, body)
	}
}
