#!/usr/bin/env bash
# Inventory + cross-check for the sites crew-cleanup knows about.
# Read-only. Deletes nothing. Run from the repo root.
#
# Output is plain text, one block per site:
#   SITE <path>
#   COUNT <n>
#   SIZE_BYTES <n>
#   OLDEST <age_days> <path>
# followed by, for sites this script knows how to cross-check, one line per item:
#   ITEM <path> LIVE=<yes|no|n/a> REFS=<n> REASON=<free text>
# and for sites it does not know how to cross-check:
#   UNCLASSIFIED <path> <reason it can't be classified>

set -u
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" || exit 1
NOW=$(date +%s)

age_days() {
  # $1 = file path -> prints integer days since mtime
  local mtime
  mtime=$(stat -f "%m" "$1" 2>/dev/null || stat -c "%Y" "$1" 2>/dev/null)
  [ -z "$mtime" ] && { echo 0; return; }
  echo $(( (NOW - mtime) / 86400 ))
}

site_summary() {
  # $1 = directory, $2 = find-args for file selection (as a string, eval'd)
  local dir="$1"; shift
  if [ ! -d "$dir" ]; then
    echo "SITE $dir"
    echo "COUNT 0"
    echo "SIZE_BYTES 0"
    echo "OLDEST 0 (directory absent)"
    return
  fi
  local files
  files=$(find "$dir" -type f "$@" 2>/dev/null)
  local count total oldest_age oldest_path
  count=$(printf '%s\n' "$files" | grep -c . || true)
  total=0
  oldest_age=-1
  oldest_path=""
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    local sz age
    sz=$(stat -f "%z" "$f" 2>/dev/null || stat -c "%s" "$f" 2>/dev/null)
    total=$(( total + sz ))
    age=$(age_days "$f")
    if [ "$age" -gt "$oldest_age" ]; then
      oldest_age=$age
      oldest_path=$f
    fi
  done <<< "$files"
  echo "SITE $dir"
  echo "COUNT $count"
  echo "SIZE_BYTES $total"
  if [ -n "$oldest_path" ]; then
    echo "OLDEST $oldest_age $oldest_path"
  else
    echo "OLDEST 0 (empty)"
  fi
}

# Reference count for a name/filename: how many hits outside the site's own directory.
# Plain grep, not rg: this script must run under a bare `bash`, where `rg` is not
# guaranteed to be on PATH (it is often a shell-only alias in the interactive session).
ref_count() {
  local needle="$1" exclude_dir="$2"
  grep -rl --fixed-strings --exclude-dir=.git -- "$needle" . 2>/dev/null \
    | grep -v "^\./${exclude_dir}/" \
    | grep -c . || true
}

echo "== .harmonik/crew/missions/ =="
site_summary ".harmonik/crew/missions" -name '*.md'
echo "--items--"
if [ -d ".harmonik/crew/missions" ]; then
  for f in .harmonik/crew/missions/*.md; do
    [ -e "$f" ] || continue
    base=$(basename "$f" .md)
    case "$base" in
      _TEMPLATE-*)
        echo "ITEM $f LIVE=n/a REFS=n/a REASON=template file, always keep"
        continue
        ;;
    esac
    live="no"
    if ls .harmonik/crew/*.json >/dev/null 2>&1; then
      if grep -l -F "$base" .harmonik/crew/*.json >/dev/null 2>&1; then
        live="yes"
      fi
    else
      live="unknown (no registry files found)"
    fi
    refs=$(ref_count "$(basename "$f")" ".harmonik/crew/missions")
    reason=""
    if [ "$live" = "no" ] && [ "$refs" -eq 0 ]; then
      reason="no live crew in the registry and no reference elsewhere"
    elif [ "$live" = "yes" ]; then
      reason="live crew in the registry"
    elif [ "$refs" -gt 0 ]; then
      reason="referenced elsewhere ($refs hit(s)) despite no live crew"
    else
      reason="registry state unknown, needs manual check"
    fi
    echo "ITEM $f LIVE=$live REFS=$refs REASON=$reason"
  done
fi
echo

echo "== .harmonik/comms/cursors/ =="
site_summary ".harmonik/comms/cursors"
echo "UNCLASSIFIED .harmonik/comms/cursors contents unaudited: no known rule distinguishes a live cursor from a stale one"
echo

echo "== .harmonik/comms/cursors-live/ =="
site_summary ".harmonik/comms/cursors-live"
echo "UNCLASSIFIED .harmonik/comms/cursors-live contents unaudited: no known rule distinguishes a live cursor from a stale one"
echo

echo "== .harmonik/cognition/ =="
site_summary ".harmonik/cognition"
echo "UNCLASSIFIED .harmonik/cognition generated by Go code; this script does not know the generator well enough to say a given file is stale"
echo

echo "== .harmonik/beads-owned/ =="
site_summary ".harmonik/beads-owned"
echo "UNCLASSIFIED .harmonik/beads-owned contents unaudited"
echo

echo "== repo root HANDOFF-*.md =="
count=0; total=0; oldest_age=-1; oldest_path=""
for f in HANDOFF-*.md; do
  [ -e "$f" ] || continue
  count=$((count+1))
  sz=$(stat -f "%z" "$f" 2>/dev/null || stat -c "%s" "$f" 2>/dev/null)
  total=$((total+sz))
  age=$(age_days "$f")
  if [ "$age" -gt "$oldest_age" ]; then oldest_age=$age; oldest_path=$f; fi
done
echo "SITE ."
echo "COUNT $count"
echo "SIZE_BYTES $total"
if [ -n "$oldest_path" ]; then echo "OLDEST $oldest_age $oldest_path"; else echo "OLDEST 0 (empty)"; fi
echo "--items--"
for f in HANDOFF-*.md; do
  [ -e "$f" ] || continue
  refs=$(ref_count "$f" ".")
  if [ "$refs" -eq 0 ]; then
    reason="no reference in skills, manifests, docs, or code"
  else
    reason="referenced ($refs hit(s))"
  fi
  echo "ITEM $f LIVE=n/a REFS=$refs REASON=$reason"
done
echo

echo "== .harmonik/context/ (*.diff and *.patch only) =="
count=0; total=0; oldest_age=-1; oldest_path=""
diffs=""
if [ -d ".harmonik/context" ]; then
  diffs=$(find .harmonik/context -maxdepth 1 -type f \( -name '*.diff' -o -name '*.patch' \) 2>/dev/null)
fi
while IFS= read -r f; do
  [ -z "$f" ] && continue
  count=$((count+1))
  sz=$(stat -f "%z" "$f" 2>/dev/null || stat -c "%s" "$f" 2>/dev/null)
  total=$((total+sz))
  age=$(age_days "$f")
  if [ "$age" -gt "$oldest_age" ]; then oldest_age=$age; oldest_path=$f; fi
done <<< "$diffs"
echo "SITE .harmonik/context (*.diff, *.patch)"
echo "COUNT $count"
echo "SIZE_BYTES $total"
if [ -n "$oldest_path" ]; then echo "OLDEST $oldest_age $oldest_path"; else echo "OLDEST 0 (empty)"; fi
echo "--items--"
while IFS= read -r f; do
  [ -z "$f" ] && continue
  refs=$(ref_count "$(basename "$f")" ".harmonik/context")
  if [ "$refs" -eq 0 ]; then
    reason="raw patch/diff, no reference elsewhere, parked in a directory a captain boot-reads"
  else
    reason="referenced ($refs hit(s))"
  fi
  echo "ITEM $f LIVE=n/a REFS=$refs REASON=$reason"
done <<< "$diffs"
