#!/usr/bin/env bash
# ctx-watchdog-launch.sh — launch the Sonnet CONTEXT-WATCHDOG.
#
# WHY (operator directive 2026-06-19, .harmonik/context/project.yaml):
#   EVERY agent session (crews, flywheel) must stay under 300k tokens. The built-in
#   session-keeper is unreliable (and its own bands are 215k/240k), so this is an
#   INDEPENDENT belt-and-suspenders watchdog: a 30-min loop that idles between ticks,
#   reads each session's .harmonik/keeper/<agent>.ctx gauge (falling back to
#   capture-pane when a crew gauge is stale), and restarts — forcibly if needed — any
#   session over the 300k cap.
#
# WHY a standalone session (NOT `harmonik crew start`):
#   A crew binds to a queue and is keeper-managed — that would entangle the watchdog
#   in the very mechanism it polices. So it's a plain `claude --remote-control`
#   Sonnet session with a minted --session-id (mirrors captain-launch.sh), no keeper
#   armed on it. Its tmux session is named `ctx-watchdog` — OUTSIDE the
#   harmonik-<hash>-* orphan-sweep namespace and NOT ending in -default, so neither
#   the daemon sweep nor a *-default guard touches it.
#
# Self-heal: the captain health-tick re-runs this script if the pane dies; the
# watchdog itself runs ctx-watchdog-respawn.sh when its OWN context nears the cap.
#
# Idempotent: re-running while the session is alive is a no-op.
#
# Usage:  ./scripts/ctx-watchdog-launch.sh   (or HK_PROJECT=/path ./scripts/ctx-watchdog-launch.sh)
set -euo pipefail

HK="${HK_PROJECT:-/Users/gb/github/harmonik}"
SESS="ctx-watchdog"
AGENT="ctx-watchdog"

# Per-project Claude Remote-Control LABEL prefix (hk-igpg). Even though the
# watchdog tmux session lives OUTSIDE the harmonik-<hash>-* namespace, the
# Remote-Control session picker is global-per-host, so prefixing the label keeps
# concurrent projects' watchdogs disambiguated (e.g. hk-ctx-watchdog vs
# mp-ctx-watchdog). Empty/absent prefix ⇒ bare label (today's behavior). The env
# var HARMONIK_AGENT stays BARE. Fetched via the read-side CLI; a CLI error is
# tolerated (|| true) → bare label.
RC_PREFIX="${RC_PREFIX:-$(harmonik remote-control-prefix --project "$HK" 2>/dev/null || true)}"
RC_LABEL="${RC_PREFIX:+$RC_PREFIX-}$AGENT"
COG="$HK/.harmonik/cognition"
PROMPT_FILE="$COG/ctx-watchdog-prompt.txt"
SID_FILE="$COG/ctx-watchdog.sid"
RESPAWN="$COG/ctx-watchdog-respawn.sh"

if tmux has-session -t "$SESS" 2>/dev/null; then
  echo "ctx-watchdog-launch: session '$SESS' already alive — no-op."
  exit 0
fi

mkdir -p "$COG"
[ -f "$PROMPT_FILE" ] || { echo "ctx-watchdog-launch: missing prompt file $PROMPT_FILE" >&2; exit 1; }

# SLEEP GUARD (hk-jxcx, codename:fleet-state): if the PRIOR watchdog session was
# intentionally parked by the daemon's QuiesceArbiter, do NOT relaunch it — that
# would un-sleep a parked session and burn tokens. The prior session-id is recorded
# in $SID_FILE; if its marker .harmonik/.sleeping.<prior-sid> is present, skip.
# The daemon owns the wake (pane nudge), not this launcher.
if [ -f "$SID_FILE" ]; then
  PRIOR_SID="$(tr -d '[:space:]' < "$SID_FILE" 2>/dev/null || true)"
  if [ -n "${PRIOR_SID:-}" ] && [ -e "$HK/.harmonik/.sleeping.$PRIOR_SID" ]; then
    echo "ctx-watchdog-launch: prior session parked (.harmonik/.sleeping.$PRIOR_SID present) — skip launch."
    exit 0
  fi
fi

# Mint a stable session-id (reused across self-heal restarts via --resume).
SID="$(uuidgen | tr '[:upper:]' '[:lower:]')"
printf '%s\n' "$SID" > "$SID_FILE"

# Generate the self-heal respawn script (same SID, re-seed the same prompt).
#
# SLEEP GUARD (hk-jxcx, codename:fleet-state): a force-restart must NOT un-sleep a
# session the daemon's QuiesceArbiter has intentionally parked. If the per-session
# sleep marker .harmonik/.sleeping.<SID> is present, SKIP the relaunch entirely —
# the daemon owns the wake (it injects a pane nudge when work arrives). Restarting
# here would un-sleep a parked watchdog and burn tokens. The SID is baked into the
# generated script, so the marker path is fixed at launch time.
cat > "$RESPAWN" <<EOF
#!/usr/bin/env bash
# ctx-watchdog-respawn.sh — GENERATED by ctx-watchdog-launch.sh. DO NOT EDIT.
# Self-heal: relaunch the watchdog resuming the SAME session-id and re-seed the loop.
set -euo pipefail
# Sleep guard (hk-jxcx): do NOT un-sleep an intentionally parked session.
if [ -e "$HK/.harmonik/.sleeping.$SID" ]; then
  echo "ctx-watchdog-respawn: session parked (.harmonik/.sleeping.$SID present) — skip restart."
  exit 0
fi
tmux kill-session -t "$SESS" 2>/dev/null || true
tmux new-session -d -s "$SESS" -e "HARMONIK_AGENT=$AGENT" \\
  "claude --dangerously-skip-permissions --model sonnet --remote-control $RC_LABEL --resume $SID"
for _i in \$(seq 1 45); do
  tmux capture-pane -p -t "$SESS" 2>/dev/null | grep -q '❯' && break
  sleep 1
done
tmux load-buffer -b ctxwd "$PROMPT_FILE"
tmux paste-buffer -p -b ctxwd -t "$SESS"
sleep 1
tmux send-keys -t "$SESS" Enter
echo "ctx-watchdog-respawn: relaunched '$SESS' (--resume $SID), re-seeded."
EOF
chmod +x "$RESPAWN"

# Launch the watchdog (Sonnet).
tmux new-session -d -s "$SESS" -e "HARMONIK_AGENT=$AGENT" \
  "claude --dangerously-skip-permissions --model sonnet --remote-control $RC_LABEL --session-id $SID"

# Wait for the claude prompt, then seed the /loop prompt via bracketed paste + Enter.
for _i in $(seq 1 45); do
  tmux capture-pane -p -t "$SESS" 2>/dev/null | grep -q '❯' && break
  sleep 1
done
tmux load-buffer -b ctxwd "$PROMPT_FILE"
tmux paste-buffer -p -b ctxwd -t "$SESS"
sleep 1
tmux send-keys -t "$SESS" Enter

echo "ctx-watchdog-launch: '$SESS' up (sonnet, rc_label=$RC_LABEL, session_id $SID); /loop seeded from $PROMPT_FILE."
echo "ctx-watchdog-launch: self-heal respawn at $RESPAWN (keeps --resume $SID)."
