package keeper

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/gregberns/harmonik/internal/core"
	"github.com/gregberns/harmonik/internal/substrate"
)

// restartnow.go — the DEAD-SIMPLE restart-now / ping path (hk-5da7).
//
// Operator design (authoritative): restart-now must be "the session id is
// verified, and you push the /clear and the agent brief command into the
// context, and be done." This replaces the elaborate marker → watcher-poll →
// nonce-poll → cycle state machine (RunOnDemand + runOnDemandCycleTail + the
// .restart-now marker) that was the source of the silent no-op bug: the CLI
// wrote a marker under os.Getwd()'s .harmonik/keeper while the watcher polled a
// DIFFERENT fixed project dir, so the marker landed where nobody looked —
// "marker written", exit 0, nothing ever happened.
//
// The new path runs SYNCHRONOUSLY in the `harmonik keeper restart-now` process
// itself: resolve the pane, verify the session id, ONE freshness check (handoff
// present and not stale), inject an ACK line (so the agent can verify receipt),
// then inject /clear and agent brief. Every step logs at INFO; any failure
// returns an error so the CLI exits non-zero and the reason is in the log. A
// silent no-op is impossible.

// RestartNowInjector is the minimal injection surface RestartNow/Ping need.
// Production wires keeper.InjectText. Tests substitute a spy. Each call submits
// the text (via bracketed paste + Enter) into the tmux pane.
type RestartNowInjector func(ctx context.Context, tmuxTarget, text string) error

// HandoffFreshnessWindow is how far BEFORE the request a handoff may have been
// written and still count as fresh. The captain writes /session-handoff and then
// calls restart-now a moment later, so the handoff mtime is naturally a few
// seconds (clock-skew + write latency) BEFORE the request — that is fresh. Only
// a handoff written meaningfully earlier (a prior session's leftover) is stale.
// A generous window avoids a clock-skew/timezone false-positive while still
// rejecting a handoff that is hours/days old. Refs: hk-5da7.
const HandoffFreshnessWindow = 10 * time.Minute

// RestartNowConfig carries everything RestartNow needs. ProjectDir + AgentName
// identify the session; TmuxTarget is the already-resolved pane; Inject is the
// injection surface (defaults to InjectText when nil); Clock defaults to
// substrate.SystemClock (overridable in tests via a substrate.FakeClock);
// RequestedAt anchors the freshness check — the handoff must be newer than
// RequestedAt - HandoffFreshnessWindow (defaults to Clock.Now() when zero).
type RestartNowConfig struct {
	ProjectDir  string
	AgentName   string
	TmuxTarget  string
	Inject      RestartNowInjector
	Clock       substrate.ClockPort
	RequestedAt time.Time

	// Emitter, when non-nil, receives a durable session_keeper_restart_now event
	// carrying the nonce on a SUCCESSFUL restart (SK-030, carry-for-audit) so the
	// self-restart is joinable to its originating cycle in events.jsonl. Nil → no
	// event is emitted (Ping never emits). The CLI wires a keeper.FileEmitter.
	Emitter Emitter
}

// Nonce is a short verifiability token echoed back to the agent in the ACK line.
// It is generated by the caller (CLI) so the agent that fired the request can
// match it. RestartNow/Ping do not invent it — they only echo it.
//
// RestartNow performs the dead-simple restart-now path. Returns nil on success
// (ACK + /clear + agent brief all injected) or an error naming the first step
// that failed (logged at WARN with the reason; the CLI maps any error to a
// non-zero exit). It does NOT consult or write any marker file — there is no
// marker in this path.
func RestartNow(ctx context.Context, cfg RestartNowConfig, nonce string) error {
	clock := cfg.Clock
	if clock == nil {
		clock = substrate.SystemClock{}
	}
	inject := cfg.Inject
	if inject == nil {
		inject = InjectText
	}
	requestedAt := cfg.RequestedAt
	if requestedAt.IsZero() {
		requestedAt = clock.Now()
	}
	log := slog.With("agent", cfg.AgentName, "op", "restart-now", "nonce", nonce)
	log.InfoContext(ctx, "keeper: restart-now: request received")

	// Step 1: a pane is mandatory — without it there is nothing to drive.
	if cfg.TmuxTarget == "" {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "no_tmux_target")
		return fmt.Errorf("keeper: restart-now: no tmux target resolved for agent %q", cfg.AgentName)
	}

	// Step 2: verify the session id (the gauge .ctx, overlaid with the
	// authoritative .sid channel). The id must be present and a trusted primary
	// (lowercase UUIDv4) — a daemon UUIDv7 or an absent id means we are not
	// looking at a real interactive captain/crew session, so refuse.
	cf, _, ctxErr := ReadCtxFile(cfg.ProjectDir, cfg.AgentName)
	if ctxErr != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "no_gauge", "err", ctxErr)
		return fmt.Errorf("keeper: restart-now: read gauge for agent %q: %w", cfg.AgentName, ctxErr)
	}
	sid := cf.SessionID
	if !IsPrimarySID(sid) {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "sid_not_primary", "sid", sid)
		return fmt.Errorf("keeper: restart-now: session id %q for agent %q is not a trusted primary id (need lowercase UUIDv4)", sid, cfg.AgentName)
	}
	log.InfoContext(ctx, "keeper: restart-now: sid verified", "sid", sid)

	// Step 3: ONE freshness check — the handoff must exist and not be stale
	// (older than the request). This is the single minimal safety gate the
	// operator kept: never /clear when HANDOFF-<agent>.md is missing or predates
	// the restart request, or we would resume from a stale/absent handoff.
	handoffPath := handoffFilePathForAgent(cfg.ProjectDir, cfg.AgentName)
	hStat, statErr := os.Stat(handoffPath)
	if statErr != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "handoff_missing", "path", handoffPath, "err", statErr)
		return fmt.Errorf("keeper: restart-now: handoff %q missing for agent %q (write /session-handoff first): %w", handoffPath, cfg.AgentName, statErr)
	}
	staleFloor := requestedAt.Add(-HandoffFreshnessWindow)
	if hStat.ModTime().Before(staleFloor) {
		log.WarnContext(ctx, "keeper: restart-now: aborted",
			"reason", "handoff_stale", "handoff_mtime", hStat.ModTime(), "requested_at", requestedAt, "stale_floor", staleFloor)
		return fmt.Errorf("keeper: restart-now: handoff %q is stale (mtime %s is older than %s before the request %s); write a fresh /session-handoff first",
			handoffPath, hStat.ModTime().Format(time.RFC3339), HandoffFreshnessWindow, requestedAt.Format(time.RFC3339))
	}
	log.InfoContext(ctx, "keeper: restart-now: handoff freshness ok", "handoff_mtime", hStat.ModTime())

	// Step 4: inject the ACK line FIRST so the agent can verify receipt before
	// the /clear wipes its context. A failure here is load-bearing: if we can't
	// reach the pane, fail loudly rather than silently /clear into the void.
	// Routed through cfg.Inject (same surface as /clear and agent brief) so
	// the whole sequence is one injectable seam.
	if err := inject(ctx, cfg.TmuxTarget, AckLine(nonce, "restart")); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "ack_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject ack: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: ack injected")

	// Step 5: /clear.
	if err := inject(ctx, cfg.TmuxTarget, "/clear"); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "clear_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject /clear: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: /clear injected")

	// Step 6: agent brief re-pins identity from soul.md (I1, provenance rule).
	if err := inject(ctx, cfg.TmuxTarget, briefRestartCmd(cfg.AgentName, cfg.ProjectDir)); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "brief_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject agent brief: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: agent brief injected; done")

	// Step 7 (additive audit, SK-030): record a durable session_keeper_restart_now
	// event carrying the nonce so the self-restart joins to its originating cycle
	// in events.jsonl by nonce. Emitted AFTER the injected sequence, so it does not
	// change the verify/ACK/clear ordering. Carry-for-audit: the nonce is never
	// validated. Best-effort — a failed audit write must not fail a restart that
	// already drove /clear+brief. Ping does not emit (nil Emitter).
	if cfg.Emitter != nil {
		payload, marshalErr := json.Marshal(core.SessionKeeperRestartNowPayload{
			AgentName: cfg.AgentName,
			SessionID: sid,
			Nonce:     nonce,
		})
		if marshalErr != nil {
			log.WarnContext(ctx, "keeper: restart-now: marshal audit payload", "err", marshalErr)
		} else if emitErr := cfg.Emitter.EmitWithRunID(ctx, core.RunID{}, core.EventTypeSessionKeeperRestartNow, payload); emitErr != nil {
			log.WarnContext(ctx, "keeper: restart-now: emit audit event", "err", emitErr)
		}
	}
	return nil
}

// Ping injects ONLY the ACK line (no /clear, no resume) so the agent can verify
// the keeper is alive and reachable. It is the minimal liveness handshake.
// Returns an error (logged at WARN) if there is no pane or the inject fails.
func Ping(ctx context.Context, cfg RestartNowConfig, nonce string) error {
	inject := cfg.Inject
	if inject == nil {
		inject = InjectText
	}
	log := slog.With("agent", cfg.AgentName, "op", "ping", "nonce", nonce)
	log.InfoContext(ctx, "keeper: ping: request received")
	if cfg.TmuxTarget == "" {
		log.WarnContext(ctx, "keeper: ping: aborted", "reason", "no_tmux_target")
		return fmt.Errorf("keeper: ping: no tmux target resolved for agent %q", cfg.AgentName)
	}
	if err := inject(ctx, cfg.TmuxTarget, AckLine(nonce, "ping")); err != nil {
		log.WarnContext(ctx, "keeper: ping: aborted", "reason", "ack_inject_failed", "err", err)
		return fmt.Errorf("keeper: ping: inject ack: %w", err)
	}
	log.InfoContext(ctx, "keeper: ping: ack injected; done")
	return nil
}

// handoffFilePathForAgent returns the conventional handoff path
// <projectDir>/HANDOFF-<agent>.md. Mirrors the default HandoffFilePath used by
// the cycle core so restart-now and the auto cycle target the same file.
func handoffFilePathForAgent(projectDir, agent string) string {
	return fmt.Sprintf("%s/HANDOFF-%s.md", projectDir, agent)
}
