package keeper

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/gregberns/harmonik/internal/core"
	"github.com/gregberns/harmonik/internal/substrate"
)

// RestartNowInjector is the minimal injection surface RestartNow/Ping need.
// Production wires keeper.InjectText. Tests substitute a spy. Each call submits
// the text (via bracketed paste + Enter) into the tmux pane.
type RestartNowInjector func(ctx context.Context, tmuxTarget, text string) error

// HandoffFreshnessWindow is how far BEFORE the request a handoff may have been
// written and still count as fresh. The captain writes /session-handoff and then
// calls restart-now a moment later, so the handoff mtime is naturally a few
// seconds (clock-skew + write latency) BEFORE the request — that is fresh. Only
// a handoff written meaningfully earlier (a prior session's leftover) is stale.
// A generous window avoids a clock-skew/timezone false-positive while still
// rejecting a handoff that is hours/days old. Refs: hk-5da7.
const HandoffFreshnessWindow = 10 * time.Minute

// RestartNowConfig carries everything RestartNow needs. ProjectDir + AgentName
// identify the session; TmuxTarget is the already-resolved pane; Inject is the
// injection surface (defaults to InjectText when nil); Clock defaults to
// substrate.SystemClock (overridable in tests via a substrate.FakeClock);
// RequestedAt anchors the freshness check — the handoff must be newer than
// RequestedAt - HandoffFreshnessWindow (defaults to Clock.Now() when zero).
type RestartNowConfig struct {
	ProjectDir  string
	AgentName   string
	TmuxTarget  string
	Inject      RestartNowInjector
	Clock       substrate.ClockPort
	RequestedAt time.Time

	// Emitter, when non-nil, receives a durable session_keeper_restart_now event
	// carrying the nonce on a SUCCESSFUL restart (SK-030, carry-for-audit) so the
	// self-restart is joinable to its originating cycle in events.jsonl. Nil → no
	// event is emitted (Ping never emits). The CLI wires a keeper.FileEmitter.
	Emitter Emitter

	// Force skips the in-flight dispatch gate (Step 3b). The auto cycle has
	// always deferred around in-flight work via Gate 5, but restart-now — the
	// operator/captain-driven path — consulted NO gate at all, so it would
	// /clear straight over a live run. Restarting mid-run cancels the crew's
	// in-flight tool work, which is the first link in the hk-bl2k6 orphan
	// chain. Force exists for the case where the operator KNOWS the marker is
	// stale and wants the restart anyway; it is deliberately explicit.
	Force bool

	// HoldingDispatchFn reports whether the agent has in-flight queue work.
	// Nil → HoldingDispatch (the .dispatching marker). Injectable so tests can
	// drive the gate without a marker file.
	HoldingDispatchFn func(projectDir, agent string) bool
}

// RestartNow performs the dead-simple restart-now path. Returns nil on success
// (ACK + /clear + agent brief all injected) or an error naming the first step
// that failed (logged at WARN with the reason; the CLI maps any error to a
// non-zero exit). It never WRITES a marker file. It does READ one: the
// .dispatching marker, as the in-flight gate at Step 3b (hk-bl2k6), which
// cfg.Force overrides.
//
// nonce is a short verifiability token echoed back to the agent in the ACK line.
// It is generated by the caller (CLI) so the agent that fired the request can
// match it. RestartNow/Ping do not invent it — they only echo it.
func RestartNow(ctx context.Context, cfg RestartNowConfig, nonce string) error {
	clock := cfg.Clock
	if clock == nil {
		clock = substrate.SystemClock{}
	}
	inject := cfg.Inject
	if inject == nil {
		inject = InjectText
	}
	requestedAt := cfg.RequestedAt
	if requestedAt.IsZero() {
		requestedAt = clock.Now()
	}
	log := slog.With("agent", cfg.AgentName, "op", "restart-now", "nonce", nonce)
	log.InfoContext(ctx, "keeper: restart-now: request received")

	if cfg.TmuxTarget == "" {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "no_tmux_target")
		return fmt.Errorf("keeper: restart-now: no tmux target resolved for agent %q", cfg.AgentName)
	}

	cf, _, ctxErr := ReadCtxFile(cfg.ProjectDir, cfg.AgentName)
	if ctxErr != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "no_gauge", "err", ctxErr)
		return fmt.Errorf("keeper: restart-now: read gauge for agent %q: %w", cfg.AgentName, ctxErr)
	}
	sid := cf.SessionID
	if !IsPrimarySID(sid) {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "sid_not_primary", "sid", sid)
		return fmt.Errorf("keeper: restart-now: session id %q for agent %q is not a trusted primary id (need lowercase UUIDv4)", sid, cfg.AgentName)
	}
	log.InfoContext(ctx, "keeper: restart-now: sid verified", "sid", sid)

	if err := checkHandoffFreshness(ctx, cfg, requestedAt, log); err != nil {
		return err
	}

	if err := checkInFlightDispatch(ctx, cfg, log); err != nil {
		return err
	}

	if err := inject(ctx, cfg.TmuxTarget, AckLine(nonce, "restart")); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "ack_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject ack: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: ack injected")

	if err := inject(ctx, cfg.TmuxTarget, "/clear"); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "clear_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject /clear: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: /clear injected")

	if err := inject(ctx, cfg.TmuxTarget, briefRestartCmd(cfg.AgentName, cfg.ProjectDir)); err != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "brief_inject_failed", "err", err)
		return fmt.Errorf("keeper: restart-now: inject agent brief: %w", err)
	}
	log.InfoContext(ctx, "keeper: restart-now: agent brief injected; done")

	if cfg.Emitter != nil {
		payload, marshalErr := json.Marshal(core.SessionKeeperRestartNowPayload{
			AgentName: cfg.AgentName,
			SessionID: sid,
			Nonce:     nonce,
		})
		if marshalErr != nil {
			log.WarnContext(ctx, "keeper: restart-now: marshal audit payload", "err", marshalErr)
		} else if emitErr := cfg.Emitter.EmitWithRunID(ctx, core.RunID{}, core.EventTypeSessionKeeperRestartNow, payload); emitErr != nil {
			log.WarnContext(ctx, "keeper: restart-now: emit audit event", "err", emitErr)
		}
	}
	return nil
}

func checkHandoffFreshness(ctx context.Context, cfg RestartNowConfig, requestedAt time.Time, log *slog.Logger) error {
	handoffPath := handoffFilePathForAgent(cfg.ProjectDir, cfg.AgentName)
	hStat, statErr := os.Stat(handoffPath)
	if statErr != nil {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "handoff_missing", "path", handoffPath, "err", statErr)
		return fmt.Errorf("keeper: restart-now: handoff %q missing for agent %q (write /session-handoff first): %w", handoffPath, cfg.AgentName, statErr)
	}
	staleFloor := requestedAt.Add(-HandoffFreshnessWindow)
	if hStat.ModTime().Before(staleFloor) {
		log.WarnContext(ctx, "keeper: restart-now: aborted",
			"reason", "handoff_stale", "handoff_mtime", hStat.ModTime(), "requested_at", requestedAt, "stale_floor", staleFloor)
		return fmt.Errorf("keeper: restart-now: handoff %q is stale (mtime %s is older than %s before the request %s); write a fresh /session-handoff first",
			handoffPath, hStat.ModTime().Format(time.RFC3339), HandoffFreshnessWindow, requestedAt.Format(time.RFC3339))
	}
	log.InfoContext(ctx, "keeper: restart-now: handoff freshness ok", "handoff_mtime", hStat.ModTime())
	return nil
}

func checkInFlightDispatch(ctx context.Context, cfg RestartNowConfig, log *slog.Logger) error {
	if cfg.Force {
		log.WarnContext(ctx, "keeper: restart-now: in-flight dispatch gate FORCED past", "agent", cfg.AgentName)
		return nil
	}
	holding := cfg.HoldingDispatchFn
	if holding == nil {
		holding = HoldingDispatch
	}
	if holding(cfg.ProjectDir, cfg.AgentName) {
		log.WarnContext(ctx, "keeper: restart-now: aborted", "reason", "holding_dispatch")
		return fmt.Errorf("keeper: restart-now: agent %q has in-flight queue work (.dispatching marker present); "+
			"wait for it to drain, or pass --force if you know the marker is stale", cfg.AgentName)
	}
	log.InfoContext(ctx, "keeper: restart-now: no in-flight dispatch")
	return nil
}

// Ping injects ONLY the ACK line (no /clear, no resume) so the agent can verify
// the keeper is alive and reachable. It is the minimal liveness handshake.
// Returns an error (logged at WARN) if there is no pane or the inject fails.
func Ping(ctx context.Context, cfg RestartNowConfig, nonce string) error {
	inject := cfg.Inject
	if inject == nil {
		inject = InjectText
	}
	log := slog.With("agent", cfg.AgentName, "op", "ping", "nonce", nonce)
	log.InfoContext(ctx, "keeper: ping: request received")
	if cfg.TmuxTarget == "" {
		log.WarnContext(ctx, "keeper: ping: aborted", "reason", "no_tmux_target")
		return fmt.Errorf("keeper: ping: no tmux target resolved for agent %q", cfg.AgentName)
	}
	if err := inject(ctx, cfg.TmuxTarget, AckLine(nonce, "ping")); err != nil {
		log.WarnContext(ctx, "keeper: ping: aborted", "reason", "ack_inject_failed", "err", err)
		return fmt.Errorf("keeper: ping: inject ack: %w", err)
	}
	log.InfoContext(ctx, "keeper: ping: ack injected; done")
	return nil
}

func handoffFilePathForAgent(projectDir, agent string) string {
	return fmt.Sprintf("%s/HANDOFF-%s.md", projectDir, agent)
}
