package daemon

// scheduler_reservation.go — the dispatch reservation write and its failure
// reporting.
//
// A reservation is the durable record that the daemon has taken a queue item
// for execution. It sets the item to dispatched and stamps the RunID that will
// execute it, in one write. Until that write is on disk the dispatch has not
// happened, and the daemon MUST NOT claim the bead or launch anything.
//
// Before this file existed the scheduler did the same job with two bare
// queue.Persist calls: the first stamped the status and an empty-string RunID
// placeholder, the second patched the real RunID in. Both ignored their error.
// A crash between the two left a dispatched item pointing at no run, and a
// failed write left the daemon launching work it had no record of.
//
// Spec ref: specs/queue-model.md §3.1 QM-001 (atomic-write failure behavior),
//
//	§9.1 QM-060 (single writer).

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/gregberns/harmonik/internal/core"
	"github.com/gregberns/harmonik/internal/handlercontract"
	"github.com/gregberns/harmonik/internal/queue"
	"github.com/gregberns/harmonik/internal/queuewiring"
)

// Reservation rejection reasons. The reservation closures return these so the
// caller can tell an item that must be failed from one where the world simply
// moved under the snapshot and the next tick should look again.
var (
	// errReserveCrossQueueDuplicate reports that another active queue already
	// holds this bead in flight. Two implementers on one bead is the failure
	// this prevents (hk-a11re).
	errReserveCrossQueueDuplicate = errors.New("daemon: reservation: bead is already in flight from another queue")

	// errReserveItemNotPending reports that the item is gone, moved, or was
	// taken by another path between the snapshot and the write.
	errReserveItemNotPending = errors.New("daemon: reservation: queue item is no longer pending")

	// errReleaseItemNotDispatched reports that the item the caller wants to give
	// back is not the dispatched item it reserved. Something else already moved
	// it, so this release has nothing to undo.
	errReleaseItemNotDispatched = errors.New("daemon: reservation: queue item is not dispatched")

	// errReleaseRunMismatch reports that the item is dispatched to a DIFFERENT
	// run than the one giving the reservation back. Releasing it would strand
	// whichever run actually holds it, so the release refuses.
	errReleaseRunMismatch = errors.New("daemon: reservation: queue item is dispatched to another run")
)

// queueReservation names the one item a dispatch wants to reserve, and the run
// that will execute it. The RunID is generated by the caller BEFORE the write,
// so that status and identity land in the same mutation.
type queueReservation struct {
	QueueName  string
	GroupIndex int
	ItemIndex  int
	BeadID     core.BeadID
	RunID      core.RunID
}

// reservationVerdict tells the scheduler what to do next.
type reservationVerdict string

const (
	// reservationReserved — the item is durably dispatched and carries its
	// RunID. The dispatch may proceed.
	reservationReserved reservationVerdict = "reserved"

	// reservationItemFailed — the item is durably failed and will not run. The
	// caller must let the group advance rather than stall on it.
	reservationItemFailed reservationVerdict = "item_failed"

	// reservationRetryLater — nothing was written. The item moved since the
	// snapshot, or another path took it. Look again on the next tick.
	reservationRetryLater reservationVerdict = "retry_later"

	// reservationWriteFailed — the write failed or its result is unknown. The
	// dispatch MUST be abandoned: no claim, no launch.
	reservationWriteFailed reservationVerdict = "write_failed"

	// reservationReleased — the item is durably back at pending and no longer
	// names a run. The next tick may pick it again.
	reservationReleased reservationVerdict = "released"

	// reservationReleaseContended — the release lost its snapshot race on every
	// attempt and gave up. The item is still dispatched to a run that is not
	// going to execute it, and nothing re-selects a dispatched item, so it is
	// stranded until the boot reconciliation pass sees it.
	reservationReleaseContended reservationVerdict = "release_contended"
)

// releaseRetryBudget bounds the release's re-snapshot loop.
//
// Transact is optimistic: it refuses a write whose snapshot moved, and raw
// writers on the per-run completion goroutines bump the generation whenever a
// run on the same queue finishes. The release MUST NOT simply give up on that
// refusal. Only a pending item is ever re-selected, so an unreleased item is
// stranded at dispatched and its group never reaches all-terminal — a stall
// that reads as a slow daemon rather than an error.
//
// The raw revert this replaces could not lose the race, because it held one
// lock across read-modify-write. It paid for that with a persist whose error it
// dropped. Re-reading and retrying buys the durability back without giving up
// the property that made the old code correct.
//
// Three is enough: each attempt re-reads the live queue, and losing three times
// means sustained contention rather than one unlucky interleave.
const releaseRetryBudget = 3

// reservationResult carries the verdict plus what the caller needs to explain
// it to an operator.
type reservationResult struct {
	Verdict reservationVerdict

	// FailureReason is the LastFailureReason written to the item, set only
	// when Verdict is reservationItemFailed.
	FailureReason string

	// ConflictingQueue names the other queue that already holds the bead, set
	// only when the item failed as a cross-queue duplicate.
	ConflictingQueue string

	// Outcome and Err are the durable result of the last write attempted.
	Outcome queue.NamespaceOutcome
	Err     error
}

// reserveQueueItem performs the dispatch reservation as one durable write.
//
// On success the item is dispatched and carries res.RunID. The two conditions
// that disqualify an item — another queue already running the bead, and the
// attempt bound — produce a durably failed item instead, because an item left
// pending after either would be re-picked on the next tick forever.
//
// It never launches anything and never claims a bead. The caller does that,
// and only when the verdict is reservationReserved.
//
// Spec ref: specs/queue-model.md §3.1 QM-001.
// Bead ref: hk-a11re, hk-dorz9, hk-6pspu, hk-xsutm.
func reserveQueueItem(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation) reservationResult {
	snapshot := queueStore.Snapshot(res.QueueName)
	if snapshot.Queue == nil {
		return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
	}

	var (
		conflictingQueue string
		maxAttemptsHit   bool
	)
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationReservation,
		Precondition:  crossQueueDuplicateGuard(res.BeadID, &conflictingQueue),
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil || item.Status != queue.ItemStatusPending {
				return errReserveItemNotPending
			}
			// hk-6pspu: count the attempt and enforce the bound. An item at the
			// bound is failed in this same write, so it leaves pending —
			// otherwise the next select re-picks it, re-counts, and dispatch
			// live-locks.
			item.Attempts++
			if item.Attempts >= maxItemAttempts {
				item.Status = queue.ItemStatusFailed
				item.LastFailureReason = "max_attempts_exceeded"
				maxAttemptsHit = true
				return nil
			}
			stampedRunID := res.RunID.String()
			item.Status = queue.ItemStatusDispatched
			item.RunID = &stampedRunID
			return nil
		},
	})

	switch {
	case result.Committed() && maxAttemptsHit:
		return reservationResult{
			Verdict:       reservationItemFailed,
			FailureReason: "max_attempts_exceeded",
			Outcome:       result.Outcome,
		}

	case result.Committed():
		return reservationResult{Verdict: reservationReserved, Outcome: result.Outcome}

	case errors.Is(result.Err, errReserveCrossQueueDuplicate):
		// The bead is already in flight elsewhere. Fail this duplicate in its
		// own write so the group advances instead of stalling on an item that
		// will never run here.
		failed := failQueueItem(ctx, queueStore, projectDir, res, "cross_queue_duplicate")
		failed.ConflictingQueue = conflictingQueue
		return failed

	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		// An earlier write to this queue failed and the store now refuses it.
		// That is the same operator problem as the write that caused it, so it
		// reports the same way. Calling it retry_later would turn a queue that
		// will never accept another write into a silent two-second spin.
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}

	case result.Outcome == queue.OutcomeRejected:
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}

	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// releaseReservation gives a reservation back through the same durable owner
// that took it. The item returns to pending and stops naming a run, in one
// write, and the caller is told whether that reached disk.
//
// A reservation is an acquire, and every acquire here has a matching release.
// The release was a raw lock-and-persist whose error was logged and dropped. A
// dropped error there means memory says pending and disk says dispatched with a
// RunID for a run that never started, and the next boot reads disk.
//
// reason is written to LastFailureReason so an operator can see why the item
// came back. Attempts is deliberately NOT reset: the budget is monotonic, so a
// bead that fails to claim forever still reaches the attempt bound (hk-6pspu).
//
// The item is identified by bead id through activeQueueItem, and by the run
// that holds it, not by slice position alone. A release that cannot find its
// own item writes nothing rather than reopening somebody else's.
//
// A failed release is reported, not fatal to the daemon: refusing to release
// strands the very item the release exists to free. The store quarantines the
// queue on a failed write regardless, so the next tick refuses it loudly.
//
// The caller MUST read the verdict. Only reservationReleased means the item is
// back; every other verdict leaves it dispatched, and a dispatched item is
// never re-selected.
//
// Spec ref: specs/queue-model.md §9.1 QM-059 (reservation release owner),
//
//	§3.1 QM-001 (atomic-write failure behavior).
//
// Bead ref: hk-mk4cl, hk-xsutm, hk-6pspu.
func releaseReservation(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation, reason string) reservationResult {
	return releaseFrom(ctx, queueStore, projectDir, queueStore.Snapshot(res.QueueName), res, reason)
}

// releaseFrom runs the release from a caller-supplied first snapshot, re-reading
// the queue after every attempt that lost the snapshot race.
//
// Seeding the first snapshot is what makes the retry testable: a test can hand
// this a snapshot it has already invalidated and watch the second attempt heal
// it. Racing a real writer for the window between the read and the write does
// not reliably reproduce a lost attempt, so a test built that way passes
// whether the loop retries or not.
func releaseFrom(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, snapshot queuewiring.Snapshot, res queueReservation, reason string) reservationResult {
	var last reservationResult
	for attempt := 0; attempt < releaseRetryBudget; attempt++ {
		if snapshot.Queue == nil {
			return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
		}
		result := releaseAttempt(ctx, queueStore, projectDir, snapshot, res, reason)
		if result.Verdict != reservationReleaseContended {
			return result
		}
		last = result
		snapshot = queueStore.Snapshot(res.QueueName)
	}
	return last
}

// releaseAttempt is one optimistic pass of the release against one snapshot.
// It is separate from the loop so a test can hand it a snapshot that is already
// stale and pin the contended classification without racing for the window.
//
// A reservationReleaseContended verdict is the ONLY one the caller may retry:
// it means the write was refused because the queue moved, not because the item
// is not ours.
func releaseAttempt(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, snapshot queuewiring.Snapshot, res queueReservation, reason string) reservationResult {
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationAdvance,
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil || item.Status != queue.ItemStatusDispatched {
				return errReleaseItemNotDispatched
			}
			if item.RunID == nil || *item.RunID != res.RunID.String() {
				return errReleaseRunMismatch
			}
			item.Status = queue.ItemStatusPending
			item.RunID = nil
			item.LastFailureReason = reason
			return nil
		},
	})

	switch {
	case result.Committed():
		return reservationResult{Verdict: reservationReleased, FailureReason: reason, Outcome: result.Outcome}

	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		// Same operator problem as the write that shut the queue, and it
		// reports the same way. See reserveQueueItem for why this is not
		// retry_later.
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}

	case errors.Is(result.Err, errReleaseItemNotDispatched),
		errors.Is(result.Err, errReleaseRunMismatch):
		// The item is not ours to give back — something else already moved it,
		// or another run holds it. Re-reading would find the same answer, so
		// this does not consume the retry budget and does not write.
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}

	case result.Outcome == queue.OutcomeRejected:
		// The snapshot moved under us: a raw writer on a completion goroutine
		// bumped the generation between the read and the write. The item is
		// still ours and still needs releasing, so the caller re-reads.
		return reservationResult{Verdict: reservationReleaseContended, Outcome: result.Outcome, Err: result.Err}

	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// activeQueueItem returns a pointer to the item at itemIdx of the active group
// with groupIndex, or nil when that item is absent or carries a different bead.
// The pointer aliases q, so the caller may mutate through it.
func activeQueueItem(q *queue.Queue, groupIndex, itemIdx int, beadID core.BeadID) *queue.Item {
	if q == nil {
		return nil
	}
	for gi := range q.Groups {
		if q.Groups[gi].Status != queue.GroupStatusActive {
			continue
		}
		if q.Groups[gi].GroupIndex != groupIndex {
			continue
		}
		if itemIdx < 0 || itemIdx >= len(q.Groups[gi].Items) {
			continue
		}
		if q.Groups[gi].Items[itemIdx].BeadID != beadID {
			continue
		}
		return &q.Groups[gi].Items[itemIdx]
	}
	return nil
}

// crossQueueDuplicateGuard builds the reservation precondition that refuses to
// reserve beadID when any OTHER active queue already holds it dispatched or
// completed. On refusal it writes the offending queue name to conflict.
//
// The check runs inside the store write lock, in the same hold as the write it
// guards. That is what makes two queues unable to reserve the same bead: the
// generation guard covers one queue name and cannot see the other one change.
//
// Bead ref: hk-a11re, hk-dorz9.
func crossQueueDuplicateGuard(beadID core.BeadID, conflict *string) func(map[string]*queue.Queue) error {
	return func(others map[string]*queue.Queue) error {
		for otherName, otherQueue := range others {
			if holdsBeadInFlight(otherQueue, beadID) {
				*conflict = otherName
				return errReserveCrossQueueDuplicate
			}
		}
		return nil
	}
}

// holdsBeadInFlight reports whether q is active and already holds beadID
// dispatched or completed. A completed item counts: the bead ran there, and
// running it again here would duplicate finished work.
func holdsBeadInFlight(q *queue.Queue, beadID core.BeadID) bool {
	if q == nil || q.Status != queue.QueueStatusActive {
		return false
	}
	for _, group := range q.Groups {
		for _, item := range group.Items {
			if item.BeadID != beadID {
				continue
			}
			if item.Status == queue.ItemStatusDispatched || item.Status == queue.ItemStatusCompleted {
				return true
			}
		}
	}
	return false
}

// failQueueItem marks one queue item failed with reason and commits that
// through the store transaction. It does not charge an attempt: callers use it
// for failures the item did not cause, such as losing a cross-queue race.
func failQueueItem(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation, reason string) reservationResult {
	snapshot := queueStore.Snapshot(res.QueueName)
	if snapshot.Queue == nil {
		return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
	}
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationAdvance,
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil {
				return errReserveItemNotPending
			}
			item.Status = queue.ItemStatusFailed
			item.LastFailureReason = reason
			return nil
		},
	})
	switch {
	case result.Committed():
		return reservationResult{Verdict: reservationItemFailed, FailureReason: reason, Outcome: result.Outcome}
	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	case result.Outcome == queue.OutcomeRejected:
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}
	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// reportQueueWriteError performs all three things QM-001 requires of a failed
// queue write. The store has already done the first — it quarantines the queue
// name, so further mutations are refused. This adds the other two: emit
// infrastructure_unavailable{failed_prerequisite: queue_write_error}, and
// declare the daemon degraded.
//
// It reports at most once per queue. The quarantine is sticky, so every later
// tick re-derives the same failure; without this bound the dispatch loop would
// emit the pair every workloopPollInterval for as long as the daemon runs, and
// the one event an operator needs would be buried in tens of thousands of
// copies of itself.
//
// The message names the queue, the outcome, and the underlying error, because
// the operator response differs: a full disk and a queue file another process
// replaced need different repairs, and neither clears by retrying.
//
// Only the outer dispatch loop calls this, so the dedup map needs no locking —
// the same single-threaded discipline as DispatchGatesPort.heldEventDedup.
//
// Spec ref: specs/queue-model.md §3.1 QM-001; specs/event-model.md §8.7.15,
//
//	§8.7.5; specs/process-lifecycle.md §4.8 PL-010.
func reportQueueWriteError(ctx context.Context, gates dispatchGatesPort, queueName string, res reservationResult) {
	detail := fmt.Sprintf("queue %q write outcome=%s", queueName, res.Outcome)
	if res.Err != nil {
		detail += ": " + res.Err.Error()
	}

	if _, reported := gates.queueWriteErrorReported[queueName]; reported {
		return
	}
	gates.queueWriteErrorReported[queueName] = struct{}{}

	fmt.Fprintf(os.Stderr,
		"daemon: workloop: QUEUE WRITE FAILED — %s. Dispatch abandoned; no bead was claimed and no run was started. "+
			"Queue %q now refuses further writes and the daemon is degraded. This does not clear by retrying: "+
			"check free disk space and the .harmonik/queues directory, then restart the daemon.\n",
		detail, queueName)

	if gates.bus == nil {
		return
	}
	emitTypedEvent(ctx, gates.bus, core.EventTypeInfrastructureUnavailable, core.InfrastructureUnavailablePayload{
		FailedPrerequisite: core.InfrastructurePrerequisiteQueueWriteError,
		DetailString:       detail,
		RetryCount:         0,
	})
	emitTypedEvent(ctx, gates.bus, core.EventTypeDaemonDegraded, core.DaemonDegradedPayload{
		DetectedAt: time.Now().UTC().Format(time.RFC3339),
		Reason:     core.DaemonDegradedReasonInfrastructureUnavailable,
	})
}

// validPayload is satisfied by every typed event payload in internal/core.
type validPayload interface{ Valid() bool }

// emitTypedEvent validates, marshals, and emits one payload, reporting each
// step's failure to stderr rather than dropping it. An event that cannot be
// emitted is exactly the case where the operator has no other signal.
func emitTypedEvent(ctx context.Context, bus handlercontract.EventEmitter, eventType core.EventType, payload validPayload) {
	if !payload.Valid() {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: payload is not valid; not emitting\n", eventType)
		return
	}
	payloadJSON, marshalErr := json.Marshal(payload)
	if marshalErr != nil {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: marshal: %v\n", eventType, marshalErr)
		return
	}
	if emitErr := bus.Emit(ctx, eventType, payloadJSON); emitErr != nil {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: emit: %v\n", eventType, emitErr)
	}
}
