package daemon

// scheduler_reservation.go — the dispatch reservation write and its failure
// reporting.
//
// A reservation is the durable record that the daemon has taken a queue item
// for execution. It sets the item to dispatched and stamps the RunID that will
// execute it, in one write. Until that write is on disk the dispatch has not
// happened, and the daemon MUST NOT claim the bead or launch anything.
//
// Before this file existed the scheduler did the same job with two bare
// queue.Persist calls: the first stamped the status and an empty-string RunID
// placeholder, the second patched the real RunID in. Both ignored their error.
// A crash between the two left a dispatched item pointing at no run, and a
// failed write left the daemon launching work it had no record of.
//
// Spec ref: specs/queue-model.md §3.1 QM-001 (atomic-write failure behavior),
//
//	§9.1 QM-060 (single writer).

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/gregberns/harmonik/internal/core"
	"github.com/gregberns/harmonik/internal/handlercontract"
	"github.com/gregberns/harmonik/internal/queue"
	"github.com/gregberns/harmonik/internal/queuewiring"
)

// Reservation rejection reasons. The reservation closures return these so the
// caller can tell an item that must be failed from one where the world simply
// moved under the snapshot and the next tick should look again.
var (
	// errReserveCrossQueueDuplicate reports that another active queue already
	// holds this bead in flight. Two implementers on one bead is the failure
	// this prevents (hk-a11re).
	errReserveCrossQueueDuplicate = errors.New("daemon: reservation: bead is already in flight from another queue")

	// errReserveItemNotPending reports that the item is gone, moved, or was
	// taken by another path between the snapshot and the write.
	errReserveItemNotPending = errors.New("daemon: reservation: queue item is no longer pending")

	// errReleaseItemNotDispatched reports that the item the caller wants to give
	// back is not the dispatched item it reserved. Something else already moved
	// it, so this release has nothing to undo.
	errReleaseItemNotDispatched = errors.New("daemon: reservation: queue item is not dispatched")

	// errReleaseRunMismatch reports that the item is dispatched to a DIFFERENT
	// run than the one giving the reservation back. Releasing it would strand
	// whichever run actually holds it, so the release refuses.
	errReleaseRunMismatch = errors.New("daemon: reservation: queue item is dispatched to another run")
)

// queueReservation names the one item a dispatch wants to reserve, and the run
// that will execute it. The RunID is generated by the caller BEFORE the write,
// so that status and identity land in the same mutation.
type queueReservation struct {
	QueueName  string
	GroupIndex int
	ItemIndex  int
	BeadID     core.BeadID
	RunID      core.RunID
}

// reservationVerdict tells the scheduler what to do next.
type reservationVerdict string

const (
	// reservationReserved — the item is durably dispatched and carries its
	// RunID. The dispatch may proceed.
	reservationReserved reservationVerdict = "reserved"

	// reservationItemFailed — the item is durably failed and will not run. The
	// caller must let the group advance rather than stall on it.
	reservationItemFailed reservationVerdict = "item_failed"

	// reservationRetryLater — nothing was written. The item moved since the
	// snapshot, or another path took it. Look again on the next tick.
	reservationRetryLater reservationVerdict = "retry_later"

	// reservationWriteFailed — the write failed or its result is unknown. The
	// dispatch MUST be abandoned: no claim, no launch.
	reservationWriteFailed reservationVerdict = "write_failed"

	// reservationReleased — the item is durably back at pending and no longer
	// names a run. The next tick may pick it again.
	reservationReleased reservationVerdict = "released"

	// reservationReleaseContended — the release lost its snapshot race on every
	// attempt and gave up. The item is still dispatched to a run that is not
	// going to execute it, and nothing re-selects a dispatched item, so it is
	// stranded until the boot reconciliation pass sees it.
	reservationReleaseContended reservationVerdict = "release_contended"

	// reservationCrossQueueCollision — another active queue holds this bead.
	// NOTHING was written: the item is still pending, and the caller decides what
	// to do from the Disposition field. This verdict is deliberately not a
	// failure. A sibling holding the bead is a property of THIS tick, and
	// specs/queue-model.md §9.8 QM-067 forbids making a per-tick refusal durable.
	// Bead ref: hk-nsion.
	reservationCrossQueueCollision reservationVerdict = "cross_queue_collision"
)

// crossQueueDisposition says what a sibling queue's hold on the same bead means
// for the reservation that lost the race.
//
// The two live values behave in opposite directions and used to be welded into
// one boolean, which is what made every collision terminal. A RUNNING sibling
// can lapse — its run ends, and the loser's item becomes reservable or its bead
// closes — so that is a refusal. A FINISHED sibling cannot lapse: the work is
// done and the bead is closed, so the loser's item is advanced to completed per
// specs/queue-model.md §3.2b QM-002b Class A rather than failed.
//
// Bead ref: hk-nsion.
type crossQueueDisposition string

const (
	// crossQueueNoCollision — no other active queue holds the bead.
	crossQueueNoCollision crossQueueDisposition = ""

	// crossQueueSiblingRunning — a sibling queue holds the bead dispatched. The
	// work is in flight there right now.
	crossQueueSiblingRunning crossQueueDisposition = "sibling_running"

	// crossQueueSiblingFinished — a sibling queue holds the bead completed. The
	// work is done; running it again would duplicate finished work.
	crossQueueSiblingFinished crossQueueDisposition = "sibling_finished"
)

// crossQueueCollision names the sibling queue that holds the bead and what its
// hold means. It is filled by the reservation precondition, which is the only
// place that can see the other queues under the same lock hold as the write.
type crossQueueCollision struct {
	ConflictingQueue string
	Disposition      crossQueueDisposition
}

// releaseOutcomeAdvice states what an operator should expect to happen next
// after a release that did not return the item.
//
// It is a function rather than a string built inline in the reporting switch
// because that report is the only place a wrong answer here reaches a human,
// and a string assembled inside a switch arm cannot be tested.
//
// The distinction it draws is load-bearing, not cosmetic. A contended release
// really does leave the item dispatched to a run that will never execute it,
// and nothing re-selects a dispatched item, so the operator waits for boot
// reconciliation. A retry_later release wrote nothing BECAUSE the item was
// already not this run's to give back: it had moved, or another run holds it.
// A double release is the ordinary producer — the first one already returned
// the item to pending, and a pending item is re-selected on the very next
// tick. Reporting that as a strand sends an operator hunting a stall that is
// not there.
func releaseOutcomeAdvice(verdict reservationVerdict) string {
	switch verdict {
	case reservationRetryLater:
		return "nothing was written because the item is not this run's to release — " +
			"it already moved or another run holds it, so this path stranded nothing"

	case reservationReleaseContended:
		return "the item is still dispatched and will not be re-selected until the boot reconciliation pass"

	default:
		// releaseAttempt does not produce reservationReserved or
		// reservationItemFailed, and reservationWriteFailed and
		// reservationReleased are reported by their own arms. An unrecognised
		// verdict is a code change that did not update this function, so say
		// the cautious thing rather than promise a recovery.
		return "the item may still be dispatched and may not be re-selected until the boot reconciliation pass"
	}
}

// releaseRetryBudget bounds the release's re-snapshot loop.
//
// Transact is optimistic: it refuses a write whose snapshot moved, and raw
// writers on the per-run completion goroutines bump the generation whenever a
// run on the same queue finishes. The release MUST NOT simply give up on that
// refusal. Only a pending item is ever re-selected, so an unreleased item is
// stranded at dispatched and its group never reaches all-terminal — a stall
// that reads as a slow daemon rather than an error.
//
// The raw revert this replaces could not lose the race, because it held one
// lock across read-modify-write. It paid for that with a persist whose error it
// dropped. Re-reading and retrying buys the durability back without giving up
// the property that made the old code correct.
//
// Three is enough: each attempt re-reads the live queue, and losing three times
// means sustained contention rather than one unlucky interleave.
const releaseRetryBudget = 3

// reservationResult carries the verdict plus what the caller needs to explain
// it to an operator.
type reservationResult struct {
	Verdict reservationVerdict

	// FailureReason is the LastFailureReason written to the item, set only
	// when Verdict is reservationItemFailed.
	FailureReason string

	// Collision names the other queue that already holds the bead and what its
	// hold means, set only when Verdict is reservationCrossQueueCollision.
	Collision crossQueueCollision

	// Outcome and Err are the durable result of the last write attempted.
	Outcome queue.NamespaceOutcome
	Err     error
}

// reserveQueueItem performs the dispatch reservation as one durable write.
//
// On success the item is dispatched and carries res.RunID. The attempt bound
// produces a durably failed item instead, because an item left pending after it
// would be re-picked on the next tick forever.
//
// A bead another active queue already holds is NOT a failure here. It returns
// reservationCrossQueueCollision with nothing written, and the caller decides:
// refuse the item for this tick, advance it to completed, or — past the
// collision bound — fail it. See resolveCrossQueueCollision.
//
// It never launches anything and never claims a bead. The caller does that,
// and only when the verdict is reservationReserved.
//
// Spec ref: specs/queue-model.md §3.1 QM-001.
// Bead ref: hk-a11re, hk-dorz9, hk-6pspu, hk-xsutm.
func reserveQueueItem(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation) reservationResult {
	snapshot := queueStore.Snapshot(res.QueueName)
	if snapshot.Queue == nil {
		return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
	}

	var (
		collision      crossQueueCollision
		maxAttemptsHit bool
	)
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationReservation,
		Precondition:  crossQueueDuplicateGuard(res.BeadID, &collision),
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil || item.Status != queue.ItemStatusPending {
				return errReserveItemNotPending
			}
			// hk-6pspu: count the attempt and enforce the bound. An item at the
			// bound is failed in this same write, so it leaves pending —
			// otherwise the next select re-picks it, re-counts, and dispatch
			// live-locks.
			item.Attempts++
			if item.Attempts >= maxItemAttempts {
				item.Status = queue.ItemStatusFailed
				item.LastFailureReason = "max_attempts_exceeded"
				maxAttemptsHit = true
				return nil
			}
			stampedRunID := res.RunID.String()
			item.Status = queue.ItemStatusDispatched
			item.RunID = &stampedRunID
			return nil
		},
	})

	switch {
	case result.Committed() && maxAttemptsHit:
		return reservationResult{
			Verdict:       reservationItemFailed,
			FailureReason: "max_attempts_exceeded",
			Outcome:       result.Outcome,
		}

	case result.Committed():
		return reservationResult{Verdict: reservationReserved, Outcome: result.Outcome}

	case errors.Is(result.Err, errReserveCrossQueueDuplicate):
		// The bead is held by another queue. Nothing is written here — this is a
		// property of the tick, not of the item, and the caller owns the choice
		// between refusing, completing and failing it (§9.8 QM-067, hk-nsion).
		return reservationResult{
			Verdict:   reservationCrossQueueCollision,
			Collision: collision,
			Outcome:   result.Outcome,
		}

	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		// An earlier write to this queue failed and the store now refuses it.
		// That is the same operator problem as the write that caused it, so it
		// reports the same way. Calling it retry_later would turn a queue that
		// will never accept another write into a silent two-second spin.
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}

	case result.Outcome == queue.OutcomeRejected:
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}

	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// releaseReservation gives a reservation back through the same durable owner
// that took it. The item returns to pending and stops naming a run, in one
// write, and the caller is told whether that reached disk.
//
// A reservation is an acquire, and every acquire here has a matching release.
// The release was a raw lock-and-persist whose error was logged and dropped. A
// dropped error there means memory says pending and disk says dispatched with a
// RunID for a run that never started, and the next boot reads disk.
//
// reason is written to LastFailureReason so an operator can see why the item
// came back. Attempts is deliberately NOT reset: the budget is monotonic, so a
// bead that fails to claim forever still reaches the attempt bound (hk-6pspu).
//
// The item is identified by bead id through activeQueueItem, and by the run
// that holds it, not by slice position alone. A release that cannot find its
// own item writes nothing rather than reopening somebody else's.
//
// A failed release is reported, not fatal to the daemon: refusing to release
// strands the very item the release exists to free. The store quarantines the
// queue on a failed write regardless, so the next tick refuses it loudly.
//
// The caller MUST read the verdict. Only reservationReleased means THIS call
// put the item back. That is not the same as the item being stranded on every
// other verdict: reservationRetryLater means the write was refused because the
// item is not this run's any more, which is what a second release of an
// already-released item gets, and that item is pending and re-selected on the
// next tick. reservationReleaseContended is the verdict that really does leave
// it dispatched, where nothing re-selects it until boot reconciliation.
// releaseOutcomeAdvice carries that distinction to the operator.
//
// Spec ref: specs/queue-model.md §9.1 QM-059 (reservation release owner),
//
//	§3.1 QM-001 (atomic-write failure behavior).
//
// Bead ref: hk-mk4cl, hk-xsutm, hk-6pspu.
func releaseReservation(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation, reason string) reservationResult {
	return releaseFrom(ctx, queueStore, projectDir, queueStore.Snapshot(res.QueueName), res, reason)
}

// releaseFrom runs the release from a caller-supplied first snapshot, re-reading
// the queue after every attempt that lost the snapshot race.
//
// Seeding the first snapshot is what makes the retry testable: a test can hand
// this a snapshot it has already invalidated and watch the second attempt heal
// it. Racing a real writer for the window between the read and the write does
// not reliably reproduce a lost attempt, so a test built that way passes
// whether the loop retries or not.
func releaseFrom(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, snapshot queuewiring.Snapshot, res queueReservation, reason string) reservationResult {
	var last reservationResult
	for attempt := 0; attempt < releaseRetryBudget; attempt++ {
		if snapshot.Queue == nil {
			return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
		}
		result := releaseAttempt(ctx, queueStore, projectDir, snapshot, res, reason)
		if result.Verdict != reservationReleaseContended {
			return result
		}
		last = result
		snapshot = queueStore.Snapshot(res.QueueName)
	}
	return last
}

// releaseAttempt is one optimistic pass of the release against one snapshot.
// It is separate from the loop so a test can hand it a snapshot that is already
// stale and pin the contended classification without racing for the window.
//
// A reservationReleaseContended verdict is the ONLY one the caller may retry:
// it means the write was refused because the queue moved, not because the item
// is not ours.
func releaseAttempt(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, snapshot queuewiring.Snapshot, res queueReservation, reason string) reservationResult {
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationAdvance,
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil || item.Status != queue.ItemStatusDispatched {
				return errReleaseItemNotDispatched
			}
			if item.RunID == nil || *item.RunID != res.RunID.String() {
				return errReleaseRunMismatch
			}
			item.Status = queue.ItemStatusPending
			item.RunID = nil
			item.LastFailureReason = reason
			return nil
		},
	})

	switch {
	case result.Committed():
		return reservationResult{Verdict: reservationReleased, FailureReason: reason, Outcome: result.Outcome}

	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		// Same operator problem as the write that shut the queue, and it
		// reports the same way. See reserveQueueItem for why this is not
		// retry_later.
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}

	case errors.Is(result.Err, errReleaseItemNotDispatched),
		errors.Is(result.Err, errReleaseRunMismatch):
		// The item is not ours to give back — something else already moved it,
		// or another run holds it. Re-reading would find the same answer, so
		// this does not consume the retry budget and does not write.
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}

	case result.Outcome == queue.OutcomeRejected:
		// The snapshot moved under us: a raw writer on a completion goroutine
		// bumped the generation between the read and the write. The item is
		// still ours and still needs releasing, so the caller re-reads.
		return reservationResult{Verdict: reservationReleaseContended, Outcome: result.Outcome, Err: result.Err}

	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// activeQueueItem returns a pointer to the item at itemIdx of the active group
// with groupIndex, or nil when that item is absent or carries a different bead.
// The pointer aliases q, so the caller may mutate through it.
func activeQueueItem(q *queue.Queue, groupIndex, itemIdx int, beadID core.BeadID) *queue.Item {
	if q == nil {
		return nil
	}
	for gi := range q.Groups {
		if q.Groups[gi].Status != queue.GroupStatusActive {
			continue
		}
		if q.Groups[gi].GroupIndex != groupIndex {
			continue
		}
		if itemIdx < 0 || itemIdx >= len(q.Groups[gi].Items) {
			continue
		}
		if q.Groups[gi].Items[itemIdx].BeadID != beadID {
			continue
		}
		return &q.Groups[gi].Items[itemIdx]
	}
	return nil
}

// crossQueueDuplicateGuard builds the reservation precondition that refuses to
// reserve beadID when any OTHER active queue already holds it dispatched or
// completed. On refusal it writes the offending queue name AND what its hold
// means to collision, because the two holds ask for opposite repairs.
//
// The check runs inside the store write lock, in the same hold as the write it
// guards. That is what makes two queues unable to reserve the same bead: the
// generation guard covers one queue name and cannot see the other one change.
//
// A RUNNING sibling wins over a FINISHED one when the scan finds both. The
// queues are walked in map order, so "first match wins" would make the reported
// disposition depend on Go's map iteration; and a bead that is completed in one
// place and dispatched in another is in flight NOW, which is the more
// restrictive of the two answers. Advancing the loser to completed on the
// strength of an older completed item would call finished work that is running
// right now done.
//
// Bead ref: hk-a11re, hk-dorz9, hk-nsion.
func crossQueueDuplicateGuard(beadID core.BeadID, collision *crossQueueCollision) func(map[string]*queue.Queue) error {
	return func(others map[string]*queue.Queue) error {
		found := crossQueueCollision{}
		for otherName, otherQueue := range others {
			switch siblingBeadDisposition(otherQueue, beadID) {
			case crossQueueSiblingRunning:
				*collision = crossQueueCollision{ConflictingQueue: otherName, Disposition: crossQueueSiblingRunning}
				return errReserveCrossQueueDuplicate
			case crossQueueSiblingFinished:
				if found.Disposition == crossQueueNoCollision {
					found = crossQueueCollision{ConflictingQueue: otherName, Disposition: crossQueueSiblingFinished}
				}
			case crossQueueNoCollision:
			}
		}
		if found.Disposition == crossQueueNoCollision {
			return nil
		}
		*collision = found
		return errReserveCrossQueueDuplicate
	}
}

// siblingBeadDisposition reports how q — another active queue — holds beadID.
//
// A dispatched item means the bead is in flight there. A completed item means
// the bead ran there and finished; running it again here would duplicate
// finished work. The two are reported separately because the dispatcher does
// opposite things with them, and the single boolean this replaced is why every
// collision used to end in a durable failure (hk-nsion).
//
// A queue that is not active holds nothing: its items cannot run, so they cannot
// collide with a dispatch happening now.
func siblingBeadDisposition(q *queue.Queue, beadID core.BeadID) crossQueueDisposition {
	if q == nil || q.Status != queue.QueueStatusActive {
		return crossQueueNoCollision
	}
	found := crossQueueNoCollision
	for _, group := range q.Groups {
		for _, item := range group.Items {
			if item.BeadID != beadID {
				continue
			}
			switch item.Status {
			case queue.ItemStatusDispatched:
				// In flight beats finished — see crossQueueDuplicateGuard.
				return crossQueueSiblingRunning
			case queue.ItemStatusCompleted:
				found = crossQueueSiblingFinished
			default:
				// pending, deferred and failed items hold nothing: none of them
				// can be executing the bead, so none of them collides.
			}
		}
	}
	return found
}

// maxCrossQueueCollisions bounds how many CONSECUTIVE times one item may be
// refused because a sibling queue holds its bead, before the refusal becomes the
// durable failure it used to be on the first collision.
//
// A refusal that never lapses is a quiet stall, and a stall reads as a slow
// daemon rather than as an error. This bound is what keeps today's loud wrong
// answer available as the tail case.
//
// It is deliberately NOT maxItemAttempts (3). Each refusal arms
// claimSkipInProgressCooldown, so the item is re-tested about every five
// minutes; a bound of 3 would fail the loser roughly fifteen minutes into a
// perfectly healthy sibling run, and that durable failure parks the loser's
// whole queue — the defect this bound sits inside the repair for. Twelve is
// about an hour of the same collision, which is long enough that the sibling is
// stuck rather than slow.
//
// Bead ref: hk-nsion.
const maxCrossQueueCollisions = 12

// crossQueueCollisionOutcome is what the dispatcher does about one collision.
type crossQueueCollisionOutcome string

const (
	// crossQueueRefuseTick — the item stays pending and is refused for this tick.
	crossQueueRefuseTick crossQueueCollisionOutcome = "refuse_tick"

	// crossQueueAdvanceCompleted — the item is advanced to completed, because the
	// sibling already finished the bead (§3.2b QM-002b Class A).
	crossQueueAdvanceCompleted crossQueueCollisionOutcome = "advance_completed"

	// crossQueueFailTerminal — the collision outlived maxCrossQueueCollisions, so
	// the item is failed with the reason it always carried.
	crossQueueFailTerminal crossQueueCollisionOutcome = "fail_terminal"
)

// crossQueueCollisionState is the in-memory record one queue item keeps between
// collisions. It follows queuePreClaimShowAttempts exactly: in memory only,
// keyed per item, CONSECUTIVE (progress deletes the entry), and forgiven by a
// daemon restart.
type crossQueueCollisionState struct {
	// consecutive counts refusals since the last time this item made progress.
	consecutive int

	// reported is the disposition already announced for this item. It is what
	// makes the collision report fire once per collision rather than once per
	// tick: a refusal repeats every poll interval for as long as the sibling
	// runs, and an event per repeat would bury the one an operator needs.
	reported crossQueueDisposition
}

// recordCrossQueueCollision folds one observed collision into states and returns
// what to do about it, plus whether this collision must be reported.
//
// It is a plain function over a plain map so the bound can be tested by calling
// it, rather than by driving a work loop for an hour of simulated collisions.
//
// A finished sibling settles the item at once and cannot repeat, so it never
// charges the bound. Any other disposition is treated as a running sibling: the
// caller only reaches this function on a collision, and a defensive third branch
// no test can reach would be worse than the totality.
func recordCrossQueueCollision(
	states map[queuePreClaimAttemptKey]crossQueueCollisionState,
	key queuePreClaimAttemptKey,
	disposition crossQueueDisposition,
) (crossQueueCollisionOutcome, bool) {
	state := states[key]
	report := state.reported != disposition
	state.reported = disposition

	if disposition == crossQueueSiblingFinished {
		states[key] = state
		return crossQueueAdvanceCompleted, report
	}

	state.consecutive++
	states[key] = state
	if state.consecutive >= maxCrossQueueCollisions {
		// Always reported: this one writes a durable failure, which is the
		// outcome an operator most needs to see and the one they can act on.
		return crossQueueFailTerminal, true
	}
	return crossQueueRefuseTick, report
}

// crossQueueCollisionSite identifies the losing queue item and stamps the time
// the collision was seen.
type crossQueueCollisionSite struct {
	QueueName  string
	QueueID    string
	GroupIndex int
	ItemIndex  int
	BeadID     core.BeadID
	Now        time.Time
}

// crossQueueCollisionPorts carries the loop state and seams the resolution needs.
// The three maps are the loop's own, passed by reference: a refusal armed here
// must be visible to the very next offerableSkipSet call.
type crossQueueCollisionPorts struct {
	emitter      handlercontract.EventEmitter
	queueStore   *queuewiring.QueueStore
	projectDir   string
	reap         reapSeamPort
	collisions   map[queuePreClaimAttemptKey]crossQueueCollisionState
	tickRefusals map[core.BeadID]bool
	refusedUntil map[core.BeadID]time.Time
}

// resolveCrossQueueCollision applies the three-way disposition of a cross-queue
// collision and reports it once. It returns true when the item was refused for
// this tick, which tells the caller it is still walking this tick rather than
// starting a new one.
//
// The three arms are the whole point of hk-nsion:
//
//   - RUNNING — the item stays pending. It is refused for this tick, so the
//     dispatcher offers the next eligible item behind it at once, and it is
//     refused for a cooldown, so the bounded poll re-examines it rather than
//     re-testing the collision every two seconds. Both are what §9.8 QM-067
//     asks for, and neither writes anything durable.
//   - FINISHED — the item is advanced to COMPLETED, per §3.2b QM-002b Class A.
//     The bead is closed and the work is done; failing the item instead would
//     park the queue over work that succeeded. Read this arm as the NARROW one:
//     the BI-013c pre-claim ledger re-read runs earlier in the same loop body
//     and advances the item on a closed bead itself (hk-rern1), so this arm
//     fires only when the ledger still reads the bead OPEN while the sibling's
//     item is already completed. That state has a real producer, not just a
//     race window: a lost close-write leaves the bead in_progress with the
//     sibling's item completed, and a startup pass then resets the bead to open
//     — QM-002b Class B, whose "no queue item references this bead" test is
//     scoped to the ONE queue being reconciled, so any sibling queue that does
//     not hold the bead reaps it; the orphan sweep of BI-010d does the same to
//     a bead whose run is gone. That the two detectors now give the same answer
//     is the point — a finished bead is never recorded as a failure, whichever
//     one sees it first.
//   - past the bound — the item is failed exactly as it always was.
//
// Spec ref: specs/queue-model.md §9.8 QM-067, §9.8a QM-067a, §3.2b QM-002b.
// Bead ref: hk-nsion, hk-a11re, hk-dorz9.
func resolveCrossQueueCollision(ctx context.Context, ports crossQueueCollisionPorts, site crossQueueCollisionSite, collision crossQueueCollision) bool {
	key := queuePreClaimAttemptKey{
		queueID:    site.QueueID,
		groupIndex: site.GroupIndex,
		itemIdx:    site.ItemIndex,
		beadID:     site.BeadID,
	}
	outcome, report := recordCrossQueueCollision(ports.collisions, key, collision.Disposition)
	if report {
		reportCrossQueueCollision(ctx, ports.emitter, site, collision, outcome)
	}

	switch outcome {
	case crossQueueRefuseTick:
		// Two refusal sets, two jobs. tickRefusals has no clock and is what makes
		// THIS tick's walk terminate. refusedUntil has one and is what stops the
		// collision being re-tested at poll cadence for as long as the sibling
		// runs. See the comments on both maps in runWorkLoop.
		ports.tickRefusals[site.BeadID] = true
		ports.refusedUntil[site.BeadID] = site.Now.Add(claimSkipInProgressCooldown)
		return true

	case crossQueueAdvanceCompleted:
		delete(ports.collisions, key)
		evaluateGroupAdvanceWithOutcome(ctx, ports.reap, site.QueueName, site.QueueID, site.GroupIndex, site.ItemIndex, true, site.Now)
		return false

	default: // crossQueueFailTerminal
		delete(ports.collisions, key)
		failQueueItem(ctx, ports.queueStore, ports.projectDir, queueReservation{
			QueueName:  site.QueueName,
			GroupIndex: site.GroupIndex,
			ItemIndex:  site.ItemIndex,
			BeadID:     site.BeadID,
		}, "cross_queue_duplicate")
		evaluateGroupAdvanceWithOutcome(ctx, ports.reap, site.QueueName, site.QueueID, site.GroupIndex, site.ItemIndex, false, site.Now)
		return false
	}
}

// reportCrossQueueCollision says on stderr and on the bus that two queues hold
// one bead, naming BOTH of them.
//
// The event exists because removing the durable failure would otherwise make a
// real misconfiguration silent. Two queues holding one bead is a planning
// mistake somebody has to fix, and neither queue name on its own tells them
// where to look.
func reportCrossQueueCollision(
	ctx context.Context,
	emitter handlercontract.EventEmitter,
	site crossQueueCollisionSite,
	collision crossQueueCollision,
	outcome crossQueueCollisionOutcome,
) {
	var disposition core.CrossQueueCollisionDisposition
	var advice string
	switch outcome {
	case crossQueueAdvanceCompleted:
		disposition = core.CrossQueueCollisionCompleted
		advice = "that queue already finished it, so this item is advanced to completed rather than run again"
	case crossQueueFailTerminal:
		disposition = core.CrossQueueCollisionFailed
		advice = fmt.Sprintf("the collision outlived %d refusals, so this item is now failed and its queue parks — "+
			"remove the bead from one of the two queues", maxCrossQueueCollisions)
	default: // crossQueueRefuseTick
		disposition = core.CrossQueueCollisionRefused
		advice = "this item stays pending and is refused until that run ends; the queue keeps dispatching the items behind it"
	}

	fmt.Fprintf(os.Stderr,
		"daemon: workloop: bead %s is held by queue %q as well as queue %q — %s (hk-nsion, hk-a11re)\n",
		site.BeadID, collision.ConflictingQueue, site.QueueName, advice)

	if emitter == nil {
		return
	}
	emitTypedEvent(ctx, emitter, core.EventTypeCrossQueueCollision, core.CrossQueueCollisionPayload{
		BeadID:       string(site.BeadID),
		LosingQueue:  site.QueueName,
		WinningQueue: collision.ConflictingQueue,
		Disposition:  disposition,
		DetectedAt:   site.Now.UTC().Format(time.RFC3339),
	})
}

// failQueueItem marks one queue item failed with reason and commits that
// through the store transaction. It does not charge an attempt: callers use it
// for failures the item did not cause, such as losing a cross-queue race.
func failQueueItem(ctx context.Context, queueStore *queuewiring.QueueStore, projectDir string, res queueReservation, reason string) reservationResult {
	snapshot := queueStore.Snapshot(res.QueueName)
	if snapshot.Queue == nil {
		return reservationResult{Verdict: reservationRetryLater, Outcome: queue.OutcomeRejected}
	}
	result := queueStore.Transact(ctx, queuewiring.TransactionRequest{
		Snapshot:      snapshot,
		ProjectDir:    projectDir,
		OperationKind: queue.OperationAdvance,
		Mutate: func(q *queue.Queue) error {
			item := activeQueueItem(q, res.GroupIndex, res.ItemIndex, res.BeadID)
			if item == nil {
				return errReserveItemNotPending
			}
			item.Status = queue.ItemStatusFailed
			item.LastFailureReason = reason
			return nil
		},
	})
	switch {
	case result.Committed():
		return reservationResult{Verdict: reservationItemFailed, FailureReason: reason, Outcome: result.Outcome}
	case errors.Is(result.Err, queuewiring.ErrQueueQuarantined):
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	case result.Outcome == queue.OutcomeRejected:
		return reservationResult{Verdict: reservationRetryLater, Outcome: result.Outcome, Err: result.Err}
	default:
		return reservationResult{Verdict: reservationWriteFailed, Outcome: result.Outcome, Err: result.Err}
	}
}

// reportQueueWriteError performs all three things QM-001 requires of a failed
// queue write. The store has already done the first — it quarantines the queue
// name, so further mutations are refused. This adds the other two: emit
// infrastructure_unavailable{failed_prerequisite: queue_write_error}, and
// declare the daemon degraded.
//
// It reports at most once per queue. The quarantine is sticky, so every later
// tick re-derives the same failure; without this bound the dispatch loop would
// emit the pair every workloopPollInterval for as long as the daemon runs, and
// the one event an operator needs would be buried in tens of thousands of
// copies of itself.
//
// The message names the queue, the outcome, and the underlying error, because
// the operator response differs: a full disk and a queue file another process
// replaced need different repairs, and neither clears by retrying.
//
// Only the outer dispatch loop calls this, so the dedup map needs no locking —
// the same single-threaded discipline as DispatchGatesPort.heldEventDedup.
//
// Spec ref: specs/queue-model.md §3.1 QM-001; specs/event-model.md §8.7.15,
//
//	§8.7.5; specs/process-lifecycle.md §4.8 PL-010.
func reportQueueWriteError(ctx context.Context, gates dispatchGatesPort, queueName string, res reservationResult) {
	detail := fmt.Sprintf("queue %q write outcome=%s", queueName, res.Outcome)
	if res.Err != nil {
		detail += ": " + res.Err.Error()
	}

	if _, reported := gates.queueWriteErrorReported[queueName]; reported {
		return
	}
	gates.queueWriteErrorReported[queueName] = struct{}{}

	fmt.Fprintf(os.Stderr,
		"daemon: workloop: QUEUE WRITE FAILED — %s. Dispatch abandoned; no bead was claimed and no run was started. "+
			"Queue %q now refuses further writes and the daemon is degraded. This does not clear by retrying: "+
			"check free disk space and the .harmonik/queues directory, then restart the daemon.\n",
		detail, queueName)

	if gates.bus == nil {
		return
	}
	emitTypedEvent(ctx, gates.bus, core.EventTypeInfrastructureUnavailable, core.InfrastructureUnavailablePayload{
		FailedPrerequisite: core.InfrastructurePrerequisiteQueueWriteError,
		DetailString:       detail,
		RetryCount:         0,
	})
	emitTypedEvent(ctx, gates.bus, core.EventTypeDaemonDegraded, core.DaemonDegradedPayload{
		DetectedAt: time.Now().UTC().Format(time.RFC3339),
		Reason:     core.DaemonDegradedReasonInfrastructureUnavailable,
	})
}

// validPayload is satisfied by every typed event payload in internal/core.
type validPayload interface{ Valid() bool }

// emitTypedEvent validates, marshals, and emits one payload, reporting each
// step's failure to stderr rather than dropping it. An event that cannot be
// emitted is exactly the case where the operator has no other signal.
func emitTypedEvent(ctx context.Context, bus handlercontract.EventEmitter, eventType core.EventType, payload validPayload) {
	if !payload.Valid() {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: payload is not valid; not emitting\n", eventType)
		return
	}
	payloadJSON, marshalErr := json.Marshal(payload)
	if marshalErr != nil {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: marshal: %v\n", eventType, marshalErr)
		return
	}
	if emitErr := bus.Emit(ctx, eventType, payloadJSON); emitErr != nil {
		fmt.Fprintf(os.Stderr, "daemon: workloop: %s: emit: %v\n", eventType, emitErr)
	}
}
